### ISSUE TITLE
How can static files be passed into the public directory?

### ISSUE THREAD

**Issue by melloradamj** [Elderjs/elderjs#10]
# How can static files be passed into the public directory during the build process?

As an example, this could be useful for:
- /robots.txt
- /favicon.ico

**Comment by nickreese** [comment]
This implementation is left up to the user. That said, in the project template it is handled in the rollup config by a glob copy of the ./src/assets/ folder. 

I’m mobile but I believe this link should take you to the relevant line: https://github.com/Elderjs/template/blob/e1448b1754ef894ff20912856e058e65381cf208/rollup.config.js#L43

**Comment by nickreese** [comment]
This would also be relatively simple to do on the 'bootstrap' hook. Going to tag this as documentation as that seems to be what is really needed here.

**Comment by nickreese** [comment]
Updated the docs and template project with an example hook to do the copying. See here: https://github.com/Elderjs/template/blob/master/src/hooks.js
