### ISSUE TITLE
Having trouble with showing validation with a hydrated contact form component

### ISSUE THREAD

**Issue by NK-WebDev** [Elderjs/elderjs#101]
Hi, for some reason my validation messages aren't being rendered when there are errors, I'm using an object to keep track of my form errors and when I change that object, the html is not being updated

the object looks like this

```js
  let errors = {
    name: null,
    email: null,
    description: null,
  };
```

and the template looks like this

```html
 <div class="form-group">
    <input placeholder="Your Name" bind:value={contactForm.name} name="name" type="text" id="name" />
    <label for="name">Name</label>
    {#if errors.name}
        <p class="error-msg">{errors.name}</p>
    {/if}
  </div>
```

I can see from the console log output that the value is being set to true when there is an error but it is not being reflected in the html.

I'm using the component like this

```svelte
<script lang="ts">
  import Banner from '../../components/Banner.svelte';
  import ContactForm from '../../components/ContactForm.svelte';
  import Container from '../../components/Container.svelte';
</script>

<Banner title="Get in touch" />

<Container />
<Container isNarrow={true}>
  <ContactForm  hydrate-client={{}} hydrate-options={{ preload: true, loading: 'eager' }} />
</Container>
```

the component code is [here in this svelte repl link](https://svelte.dev/repl/0b96b12bd73a46879cf21e0afe236a24?version=3.29.7) It's working in the svelte repl

If you need more context then this is [the actual file in my project](https://github.com/NK-WebDev/studiodagger-elderjs/blob/contact-form/src/components/ContactForm.svelte)

If you have an example or some guidelines on using elderjs for form validation then that would be helpful.

**Comment by nickreese** [comment]
@NK-WebDev this is a svelte issue. I know it works in the repl but it comes down to the way you are mutating object keys and Svelte is not detecting the change. https://svelte.dev/tutorial/updating-arrays-and-objects

**Comment by NK-WebDev** [comment]
Thanks for the quick reply and the link to the correct docs, I tried just using variables like nameError = null, instead of an errors object but it didn't work that time, I guess because the server didn't update for some reason but now it works if I just use a primitive variable instead of an object or make another extra assignment or a new copy. It's weird that in the repl we don't have to do this. :confused: 

If anyone else is stuck with a similar problem any one of this will work

```
nameError = null;

// validation 
nameError = 'name is not valid'
```

```
errors = {
	name: null
	.
	.
	.
}

//validation
errors = {
	...errors
	name: 'name is invalid'
}
```


```
errors = {
	name: null
	.
	.
	.
}

// validation

errors.name = 'name is unvalid'

// other validation
.
.
.


// finally an extra assignment
errors = errors
```

**Comment by NK-WebDev** [comment]
thanks for the quick reply and sharing the correct documentation link, I got it to work by creating a new copy of the object like this
```js
errors = {
	...errors
	name: 'name is invalid'
}
```

I thought it might be because I was mutating the object property so I had previously tried to do it this way and it didn't work, now I know that it didn't work because for some reason the compiled code hadn't updated properly so I manually deleted the __ELDER__ folder, made my changes and restarted rollup and nodemon server.

I tried my previous code on a brand new svelte app and it is working fine there, the svelte tempplate uses svelte 3.0.0 and my elder.js app is using svelte 3.24.0, idk if it is because of this or something else, @nickreese do you know why it's working with a new svelte app but not with elder.js?

**Comment by nickreese** [comment]
@NK-WebDev Elder.js is just a wrapper around Svelte’s mount code. If you’re really curious about the root cause look into the differences in output that Elder and the new svelte template generate.
