### ISSUE TITLE
Rollup doesn't auto-compile upon new components and modifying js

### ISSUE THREAD

**Issue by s-kris** [Elderjs/elderjs#104]
1. Rollup doesn't automatically compile newly added components always. We need to restart everytime.
2. Changes in components containing js that are hydrated are not reflected sometimes.

To confirm the issue, I saw the talk on https://www.youtube.com/watch?v=R9oPCfd1FB8 timestamp: 17:40
Is this a common issue with many people?
Thanks for this awesome framework!

Node: 14.4.0
Rollup: 2.21.0
Svelte: 3.24.0
elderjs: 1.1.7

**Comment by nickreese** [comment]
@s-kris there are two different issues going on. I’d encourage you to try the latest Elder.js. 

While you will always have to restart rollup when adding new components file interdependence has been completely overhauled in 1.2.2.

**Comment by s-kris** [comment]
Thank you @nickreese

**Comment by timeshift92** [comment]
It does not work for me
elderjs: 1.3.4
