### ISSUE TITLE
Proposal: add a hook similar to `allRequests` but after permalinks have been set

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#106]
## Why I need this ?
In my i18n plugin, I would like to manage the case where an international site is on several domains.
To do this, you can add another origin to a locale and then exclude the generation of pages with this locale. But I want to keep the ability to have a link to theses pages.
Next to that, I create a request dictionary to be able to access the same "page" but with a different locale (which allows to have a locale switcher).
I implemented both in `allRequests` hooks but I lose  the "exclude locales permalinks" (that should be call link in this case) ans hreflang also.

## Other use case
This is related to incremental builds #8 , I don't know where you stand on this, but if we keep the idea of using a plugin or at least the hook system to manage this feature, we'll also need to have access to the permalink of the non-generated pages in case it's used in the generated ones. 
## Thought about it
At the moment elderjs is checking that there are no issues with requests after `allRequests` before adding the permalinks, which makes absolute sense. If we allow to modify requests after that, we should check again that everything is ok.

Another possibility is to  consider that the purpose of this hook is only to delete requests and to not allow any to be added; while keeping a copy of what has been deleted for a separate use (in our case, recovering the missing permalinks). It would introduce a new mechanism to hook's "contract" alongside mutability, something similar to `destructuring assigment` (I don't know any closer pattern).

The idea is that, for an array prop, instead of returning an array with the new values as we do for mutability, we would return the values to be deleted. 

This would give for example:

```javascript
{
  hook: 'destructRequests',
  name: 'i18nExcludeLocales',
  description: 'Remove requests according to excludeLocales config',
  priority: 100,
  run: async ({ allRequests, plugin }) => {
    return {
      allRequests: allRequests.filter((request) => plugin.config.locales.excludes.includes(request.locale)),
    };
   },

```

### EDIT: Second though
I was thinking about incremental building, if we go the way I  describe, it can be nice to add some lazyness to the "deleted requests" permalink, but that's optimization I guess.

**Comment by nickreese** [comment]
@kiuKisas interesting. I don’t think I fully follow. 

That said, could the issue be solved if the `requests` returned from `allRequests` could have permalink set on them directly... and Elder.js detects that and doesn’t run the `permalink` function?

I’m weary of adding additional hooks.  Especially special purpose hooks.

**Comment by kiuKisas** [comment]
It can be solved this way. In this case, elderjs will need to take care of new requests (without permalink yet) added by the same hook (e.g: elder-plugin-markdown).
 I first though it would add more complexity in the data flow, that's why I propose to separate this in two hooks: one to add requests (current `allRequests`) and another to delete (and "cache" if needed later) ; but  I understand your weariness regarding new hooks, we should avoid them I guess. 
I apologize if I confuse you, I get quickly excited sometimes about new features and my broken english doesn't help ^^'

**Comment by nickreese** [comment]
Your English is great. Better than my other languages. :) 

Thinking more on your goal. For the pages you want to cache but not create why not keep them in the plugin context and just have your permalink helper just use that as the source?

So the permalink helper would use allRequests AND and any cached permalinks you needed.

**Comment by kiuKisas** [comment]
If someone is interested, I use the `routes` props to recreate the `request` there: https://github.com/kiuKisas/elderjs-plugin-i18n/blob/86fb5617cf2c0c4aa1056e79f6d7bb810077a768/utils.js#L59

Closed.
