### ISSUE TITLE
Duplicate permalinks when sharing data object

### ISSUE THREAD

**Issue by paulhovey** [Elderjs/elderjs#108]
Hi, I've been tinkering around with elderjs and have gotten stuck on an issue where I'm creating duplicate permalinks.  I don't think elderjs is behaving as I expect it to, but perhaps I'm not using elderjs in the way it was meant to be used either!

Repo demonstration (based off template):  https://github.com/paulhovey/elderjs-route-bug/commit/099f92525f974d6cf2833ed2e6b869b9ba48cbdd

Essentially, I have an array in my data object that I populate once in hooks.js (going to be using a database, in the example it's just a hardcoded array).  

`let simpleRoutes = [{name: 'testdata1', slug: 'simple' },
            {name: 'testdata2', slug: 'simple2' }];`

The goal is to generate /simple/simple , /simple/simple2, /simpletwo/simple, and /simpletwo/simple2 , if that makes sense.  I'm realizing now I could've named those differently for the example :sweat_smile: 

It appears that the first route (in the example, 'simple') gets added correctly, but the 'route' key is added to the object in 'data', and then isn't being updated for the second route.  A hack debug message inside of simpletwo/route.js: all() yields:

`data in simpletwo:  {
  markdown: { blog: [ [Object], [Object], [Object] ] },
  simpleRoutes: [
    { name: 'testdata1', slug: 'simple', route: 'simple' },
    { name: 'testdata2', slug: 'simple2', route: 'simple' }
  ]
}`

I don't think `route: 'simple'` should be there!  I've tried looking through the most likely culprit ( https://github.com/Elderjs/elderjs/blob/34e54d26e0eb2b4c0fe517b9343b46ccc69b16eb/src/Elder.ts#L275 ) but nothing _looks_ immediately faulty to me.  If this is abusing how elderjs is supposed to operate and there's a better way to generate the same slugs for two routes, then I'd appreciate the insight there!  Thanks!

**Comment by nickreese** [comment]
@paulhovey Sorry for the delay on this. 

This has to do with JS' pass by reference on objects. 

We could in theory use `allRequestsForRoute = JSON.parse(JSON.stringify(route.all));` but I fear that would break lots of sites unexpectedly.

**Comment by nickreese** [comment]
OK, I've got a fix. Will push with next release.

**Comment by paulhovey** [comment]
Thanks so much, @nickreese !
