### ISSUE TITLE
Accessing the current request in a component

### ISSUE THREAD

**Issue by Munter** [Elderjs/elderjs#109]
I am trying to build a menu component, and in order to improve accessibility, I'd like to add an `aria-current="page"` on the currently active route: https://tink.uk/using-the-aria-current-attribute/

I haven't been able to figure out what the current request is inside a component. Is there a way to do this?

Is there maybe a different way of achieving my goal?

**Comment by nickreese** [comment]
Both Layouts and Templates have access to the `request` object. Check to see if the permalink maches and output your code if so.

**Comment by Munter** [comment]
I was hoping to avoid doing prop-drilling this information down the component hierarchy to my navigations. But I guess I can attempt to flatten the hierarchy a bit to avoid prop-drilling too much
