### ISSUE TITLE
Style changes remove all styles

### ISSUE THREAD

**Issue by stefan-contiero** [Elderjs/elderjs#114]
Full disclosure: I'm new to Svelte and Elder.js, so I might be missing something obvious.

I found an odd behavior when changing styles:

Whenever I change any style property in a `.svelte` file, the whole style declaration for the file disappears from the page.
On save, both rollup and nodemon work as expected, and the page is reloaded.
Anyhow, the styles for the component completely disappear.
The only way to restore them is to stop and re-run rollup, refresh the page, and only then, the style changes are available.

I was able to reproduce the problem by creating a new project and changing only the `.banner` background color in the `Home.svelte` file.

Here are the steps:
1) Run:
```
npx degit Elderjs/template elderjs-app
cd elderjs-app
npm install
npm run dev:rollup
npm run dev:server
```
2) Open `src/routes/home/Home.svelte` and change line 16 to `background: red;`
3) Save and observe styles disappear from Home

My hunch is that this has something to do with the scoped styles, as `:global()` declarations are unaffected, and undoing the changes restore the original styles.

If relevant:
```
macOS 11.0.1
node v15.5.0 (also tried with v12.18.0)
npm v7.3.0 (also tried v6.4.8)
rollup: 2.33.3
svelte: 3.29.0
elderjs: 1.2.1
```

In any case, really love the project! Thanks for open sourcing this, looking forward to using it for my website. 🙏

**Comment by kiuKisas** [comment]
Hey, same issue, except that the page is not reloaded when I save my change (but rollup and nodeman seems to reload in my terminals)
```
Arch linux 
node: 14.15.1
yarn: 1.22.10
rollup: 2.21.0
svelte: 3.29.0
elderjs: 1.2.4
```

**Comment by kiuKisas** [comment]
It doesn't happen everytime, I try to figure it out when it happens, so here is a list of when this bug happen (I will edit it if I find other case):
## Components
- changing property style work, (e.g: height: 60px to height: 70px). However, going back to the initial style (when I launch dev:rollup and dev:server) partially broke style (e.g: going back to height: 60px)
- if I add a property to the previous example (e.g: background-color), it works as expected and fix the previously broken style. If I delete the background-color, it's broken again.
## svelte file in routes folder
- If I delete one selector, all the style is not apply anymore. (e.g: h2 and textarea style, if I delete h2, the style for textarea is not apply anymore)
- same if I remove one property (e.g: deleting font-familly on h2 disable all the style from my component)
## global style (style.css)
- seems to work as expected

But auto-reload doesn't  work on firefox or chromium for me

**Comment by nickreese** [comment]
@kiuKisas Thanks for digging into this. It sounds like it is related to the (rollup plugin's watch file logic](https://github.com/Elderjs/elderjs/blob/master/src/rollup/rollupPlugin.ts#L254) or the [in memory cache we're using](https://github.com/Elderjs/elderjs/blob/master/src/rollup/rollupPlugin.ts#L283) to speed up reload times... or a mix of the two.

My best guess is that when the hash of the file changes, the CSS is not getting updated or a dependency that we're tracking isn't getting updated. 

I have recently seen this bug in the wild so I know it exists. Would love help here to fix it as I have limited bandwidth for the next little bit so won't have a chance to dig into it. 

--

Also is this happening when writing css to a file or just to the component?

**Comment by Agedjus** [comment]
I created an issue in template repository, probably related to this: https://github.com/Elderjs/template/issues/38

**Comment by nickreese** [comment]
@Agedjus @kiuKisas @stefan-contiero pushed a fix for this.
