### ISSUE TITLE
Reload doesn't work unless origin is set to localhost:3000

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#117]
Hey,
I noticed that when I change my origin to `localhost:3000`, page reloading works. (and doesn't with https://test.fr)

**Comment by nickreese** [comment]
@kiuKisas since the reloading is designed to be a development only tool it has a separate origin control within the plugin:

Origin wasn't documented in the readme. Now it is. 

```
  '@elderjs/plugin-browser-reload': {
    origin: 'http://localhost',
    port: 8080, // the port the websocket server should run on.
    delay: 200, // the delay in ms the browser should wait after the server disappears.
    preventReloadQS: 'noreload', // if 'noreload' is in the query string it won't reload that page. Good for CSS editing in the browser.
    retryCount: 50, // number of tries the browser will check to see if the server is up before giving up.
  },
```

**Comment by kiuKisas** [comment]
Thank's ! 
So my issue was due to not having set the origin in `plugin-browser-reload`, so the plugin take my `settings.origin`, according  to this line:
 https://github.com/Elderjs/plugins/blob/b81e44ed6dd5a48f5bb974b87821c5b4c2e90ddf/packages/browser-reload/index.js#L11
 To prevent this, adding  `origin: 'http://localhost'` to [elderjs/template](https://github.com/Elderjs/template) seems to be a good idea.
