### ISSUE TITLE
Documentation on intersection observer and systemjs

### ISSUE THREAD

**Issue by philipp-tailor** [Elderjs/elderjs#12]
Attempted to adapt elderjs for a mostly static blog. I detected that elderjs doesn't suit my needs only after being close to done with the migration: Client side svelte components are only loaded and hydrated once they are part of the viewport, detected via intersection observer. This should be clearly stated in the documentation. I'd open a PR to update the documentation myself, if I'd know the exact reasoning behind this decision. I assume that the design decision was taken as a performance optimisation / viewing dynamic components as progressive enhancement. But for the full picture it's simpler if the maintainers directly update the docs and close this issue.

In the same vain (another default behaviour that isn't really reasoned about) is the usage of systemjs. Here I assume that it's to have IE11 support for interactivity?

This issue is about adding the documentation.

I'm also happy to share the example why the intersection observer thing – if not deactivatable – is a deal-breaker to me.

**Comment by nickreese** [comment]
So digging back into my notes when developing early versions of Elder.js we decided to go with systemjs for wide browser support. 

Upon further exploration I think we could use systemjs as a fallback and esm as the default by adapting some of the patterns seen in this repo: https://github.com/rollup/rollup-starter-code-splitting

This is a pretty big refactor but it would mean modern browsers get ESM and legacy browsers get systemjs. 

This adds more complexity to our rollup config and the svelteComponent.ts but should be manageable. 

I’d like to explore if we could then use snowpack or another bundler during dev.
