### ISSUE TITLE
GitHub Pages can't find paths beginning with _

### ISSUE THREAD

**Issue by macabeus** [Elderjs/elderjs#121]
Elder.js builds a folder called `_elderjs` and uses it on the assets.
But [GitHub Pages won't store paths beginning with underscore](https://stackoverflow.com/a/39937443/3440266), needing to rename it to just `elderjs`.

Is there a way to change this folder name while building? I can't find it on the doc.

**Comment by nickreese** [comment]
@macabeus How does `_next` address this? That seems very strange. At this point there isn't a way to change the internal elder output dir as we need to be able to make assumptions about where the files will live.

**Comment by macabeus** [comment]
@nickreese Is possible to solve it by adding a [`.jekyll`](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/) file on the root.
Would make sense to add an option on Elderjs to output this file?

**Comment by nickreese** [comment]
@macabeus I think we should just document it in the docs. If you could add how you got it to work to the FAQ that would be awesome: https://github.com/Elderjs/docs/blob/master/elderguide.com/elderjs.md
