### ISSUE TITLE
Question: Shared State between pages?

### ISSUE THREAD

**Issue by schnubor** [Elderjs/elderjs#122]
Hi everyone!

Thanks for making and maintaining elder.js, I love it so far :)

I couldn't find something in the docs regarding this topic, so here is my question:

**Is there a n elegant elder.js way to save user generated data between pages?**

Quick example: I have a site/route with 2 Buttons on them that both lead to a "Result" page, showing me which of the 2 buttons has been clicked on the previous page.

Another example: I have a survey site,with 3 question pages each linking to the next one. I want to save the answers given on each page and then show a fitting result page. Where to save to answers?

Thanks,

Christian

**Comment by kiuKisas** [comment]
What you ask for seems to not concern the SSG part, what elderjs main purpose is, but SSR/client-side which is manage through svelte. 
My guess is you should go with [hydratation](https://elderguide.com/tech/elderjs/#partial-hydration) on the concern component, through your layout, and using svelte store or something similar.
I didn't try myself but it seems the way to go. Let us know if you made progress on this :)

**Comment by schnubor** [comment]
Thanks for the suggestion. I kinda expected something along those lines, but svelte stores won't work across routes, or at least I didn't get it to work the way I wanted it to work. Anyway I use hydration on the Answer components of my survey.

My current solution is just to defer to `sessionStorage`. I use hydration on my Answer components within my survey to populate the storage. Other possible global "stores" would be `history.state` or even `localStorage` (larger scope).

**Comment by kiuKisas** [comment]
Seems a good approach. Let's wait for @nickreese answer about svelte store (or similar) across routes, it can be really really nice to have but I'm afraid it's out of scope, it seems an SPA feature to me.

**Comment by nickreese** [comment]
@schnubor @kiuKisas The canonical way to do this in traditional SSR languages is to pass query parameters. I'd suggest going that route if your state isn't overly complex. If it is overly complex cookies and even `localStorage` are decent options. 

I use query params on ElderGuide.com when you choose certain zip codes: https://elderguide.com/senior-living/finder/?lat=37.81&lon=-75.57&expanded=true&within=true&show=all

The query params seed the state, then I have a little helper to update the URL params to persist things between loads and make sure things are sharable... but it basically performs as a SPA without the client side routing wizbang.

**Comment by schnubor** [comment]
I ended up with a hydrated <Store> on each route component thats handling some stuff in the sessionStorage and it's working good so far. I think we gathered more than enough options here now so I'm closing this.

Thanks guys! :)
