### ISSUE TITLE
Proposal: version compatibility for plugins

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#123]
As the project will evolve, new features will be introduce and some plugins may not work on older version. For example, my i18n-plugin required at least 1.2.5 to work properly. 
It can be nice to add a minimal required version variable in plugins settings, to prevent the use of incompatible plugin and display a message about it.

**Comment by nickreese** [comment]
Great idea. 

At the surface this appears to be adding a check during plugin init in `Elder.ts` and adding requirements for plugins to include a version in their definition. If the definition isn't present I'm assuming we'd want to just pin it to the first version of Elder.js that required it.

Happy to review a PR on this.

**Comment by nickreese** [comment]
@kiuKisas This was added in `1.4.13` as `minimumElderjsVersion`. Not sure why your PR got closed. I ended up rolling my own basic semver check just to avoid another dep.
