### ISSUE TITLE
Possible memory leak with PerformanceObserver

### ISSUE THREAD

**Issue by bbuhler** [Elderjs/elderjs#127]
Hi guys 👋️

After we switched our production landing page to ElderJS we noticed a drop in free memory over time until the instance is not responding anymore and get restarted.

![image-2021-01-19-10-49-57-875](https://user-images.githubusercontent.com/2802675/105828759-cbf49f80-5fc3-11eb-9b83-3c9947fb3d5c.png)

We ran the server locally with node inspector to identify the cause and found out that one of the bigger retainers is an internal array with strings starting with "hook." in the context of `perf.js`.

<details>
<summary>📷️ Screenshot of devtools memory analyses of node server</summary>

![Screenshot of devtools memory analyses of node server before change](https://user-images.githubusercontent.com/2802675/105829950-39550000-5fc5-11eb-9da4-2b8432a9e46a.png)

</details>

In our `elder.config.js` we have `debug.performance` set to `false` though it still seems to collect the performance metrics without using it.

For testing purpose we commented out the `PerformanceObserver` and the calls to it in `perf.js`. Now we see a much lower retained memory.

<details>
<summary>📷️ Screenshot of devtools memory analyses of node server after change</summary>

![Screenshot of devtools memory analyses of node server after change](https://user-images.githubusercontent.com/2802675/105838649-a91cb800-5fd0-11eb-9652-3d5f6652538d.png)

</details>

**Comment by nickreese** [comment]
@bbuhler Yep, looks like a memory leak. Thanks for calling this out. Will dig into this shortly.

**Comment by nickreese** [comment]
@bbuhler This will be fixed next release (should be today).
