### ISSUE TITLE
Make HTML template configurable: (Make <head> tag fully customizable)

### ISSUE THREAD

**Issue by jbmoelker** [Elderjs/elderjs#13]
👏 for starting a static site generator using a modern framework with 0kb client-side JS by default and optional client-side hydration!

Currently the [HTML template is statically defined in `Page.ts`](https://github.com/Elderjs/elderjs/blob/4f51fa443f8dfdbada75775f0c3d378ea624a143/src/utils/Page.ts#L88-L103):
```js
    page.htmlString = `<!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          ${page.headString}
        </head>
        <body class="${page.request.route}">
          ${layoutHtml}
          ${page.hydrateStack.length > 0 ? page.beforeHydrate : '' /* page.hydrateStack.length is correct here */}
          ${page.hydrateStack.length > 0 ? page.hydrate : ''}
          ${page.customJsStack.length > 0 ? page.customJs : ''}
          ${page.footerStack.length > 0 ? page.footer : ''}
        </body>
      </html>
    `;
```

It would be great if this template would be configurable, so for instance `html[lang]` could easily be changed.
Maybe this can be offered through a hook, or by introducing a [`src/template.html` file like in Sapper](https://sapper.svelte.dev/docs#src_template_html).

This would help with #6, as I'm currently forced to overwrite the `html[lang]` with a hook:

```js
  {
    hook: 'html',
    name: 'setHtmlLang',
    description: 'Overwrite html[lang="en"] with html[lang="{ request.locale }"]',
    priority: 50,
    run: ({ htmlString, request }) => {
      return {
        htmlString: htmlString.replace('<html lang="en">', `<html lang="${ request.locale }">`),
      };
    },
  },
```

**Comment by nickreese** [comment]
@jbmoelker So the more I've thought about this the more I believe your current hook implementation is actually the desired one until there is a more fully fleshed out plan for i18n and community plugins supporting it.

That said, another possible low hanging fruit solution would be to have Elder.js look for a `request.locale` or `request.lang` and set the value there on the html. If it doesn't exist it defaults to `<html lang="en">`.

I think living this issue open for more conversation about customizing the HTML template is worthwhile. If anyone reading this has ideas, we'd love to hear them.

**Comment by nickreese** [comment]
@jbmoelker I'm going to close this as I think a hook is the correct way to solve this specific issue.

**Comment by jbmoelker** [comment]
Hi @nickreese, you raise some good questions :) I'm not sure how you could pass more data to a Sapper template (I wasn't too satisfied with Sapper and haven't used it much since). I'm not sure I'm a big fan of my own solution using string replace in a hook. I imagine a hook could still work. It would maybe be nice if `page.htmlAttributes` would be available inside hooks, so you can properly manipulate them rather than having to use string replace / regex matching.

**Comment by nickreese** [comment]
@jbmoelker that wasn’t a solution I considered. What how would you suggest it on? `request`?

**Comment by akvadrako** [comment]
> I think living this issue open for more conversation about customizing the HTML template is worthwhile. If anyone reading this has ideas, we'd love to hear them.

Does that mean it would be appropriate to open a new issue to continue this discussion?

I would like to change the `"viewport"` meta tag. I think it would be great if you would just remove the meta tags from the template:

```html
        <head>
          ${page.headString}
        </head>
```

They can anyway be easily customized in the `<svelte:head>` tags.

**Comment by nickreese** [comment]
@akvadrako Totally doable. We'll add `<meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />` as defaults that can be disabled by disabling the hook. The majority of the discussion was mainly about the `<html` tag.

**Comment by nickreese** [comment]
@akvadrako [Initial commit here](https://github.com/Elderjs/elderjs/commit/0fe54d477f4a37f2864a1e15a7356c1f52e7fda0), but for the sake of future proofing and remembering somewhere that the char encoding should always be first, I'm going to break these into two different hooks before releasing.

**Comment by nickreese** [comment]
@akvadrako pushed with [v0.1.5](https://github.com/Elderjs/elderjs/releases/tag/v0.1.5). Also fixed a bug where stacks were being processed backwards. 

Doesn't fix the HTML lang issue, still open to coming up with a more official plan.

**Comment by nickreese** [comment]
For anyone that finds this, if you want to remove both meta tags, add `elderAddMetaCharsetToHead` and `elderAddMetaViewportToHead` to your hooks.disable array in your `elder.config.js`.

**Comment by akvadrako** [comment]
@nickreese thanks for the quick fix. It's working well for me.

**Comment by nickreese** [comment]
This will be in v1. Elder.js now uses the `compileHtml` hook which the user can disable and add their own template.
