### ISSUE TITLE
Quesiton re: 0KB JS

### ISSUE THREAD

**Issue by markshlick** [Elderjs/elderjs#133]
Hi all, great work!  I'm very curious about how you're able to determine whether to ship JS or not, and would love to learn how to leverage this feature.  Do you perform some static analysis on the Svelte components, or does the author need to specify some flag on the component/route?

**Comment by nickreese** [comment]
@markshlick We use a tag that Elder.js picks up to do partial hydration: https://elderguide.com/tech/elderjs/#partial-hydration. If no components are hydrated then the page will have 0KB JS.
