### ISSUE TITLE
Trouble using image plugin

### ISSUE THREAD

**Issue by ramshorst** [Elderjs/elderjs#135]
Hi there ! Elder JS is awesome. I use it in production on a 1000+ pages website currently. I love it. 

I ran into a problem recently. I cannot use the images plugin.
Rollup throws an error as soon as it sees a shortcode.

I have made changes to the `shortcodes` `openPattern` and `closePattern` in the past, but even avec changing it back it does not work.

<img width="328" alt="Screenshot 2021-02-10 at 00 35 35" src="https://user-images.githubusercontent.com/5200239/107443205-aecdde00-6b38-11eb-8a61-1f54531f89f9.png">

Did anyone run into this problem before ?

**Comment by kiuKisas** [comment]
I have the same error, are you on linux ? see #124 
I temporally set the `openPattern` to `%%`, I will dig into this issue when I'll have time but feel free to have a look.
Close this issue in favor of #124

**Comment by ramshorst** [comment]
Hi @kiuKisas !
I am on MacOS.
Changing the openPattern seems to 'resolve' the problem on my site two.
