### ISSUE TITLE
Question about client side hydration

### ISSUE THREAD

**Issue by myrsmedenstorytel** [Elderjs/elderjs#136]
Hello! Is there any way we can know if a component is being server-rendered or client hydrated?
For my particular use-case, I do not want to load images when server rendering but do so when the component is hydrated in the client.

Something like this:
```
// HydratedComponent.svelte

import Image from 'ImageComponent.svelte'
...
<Image lazyLoad={inServerRenderMode} />
...
```

**Comment by nickreese** [comment]
https://github.com/Elderjs/elderjs/blob/902d7f4352d50091f10d38314141462f112895a4/src/rollup/getRollupConfig.ts#L53

Is the relevant code. In the hospital so can’t update the docs. There is a matching one for the server. Feel free to PR the docs if you have time.

**Comment by myrsmedenstorytel** [comment]
Thanks for your reply! If you have the opportunity to make me a contributor for the docs project I can make the PR. But it's no rush. Hope you get better soon!
