### ISSUE TITLE
Looking for help

### ISSUE THREAD

**Issue by nickreese** [Elderjs/elderjs#138]
Hey crew, as I’ve shared with some of you I’ve been going through some pretty serious health issues. 

I’m back in the hospital and want to make sure this project is in good hands so I’d like to add a maintainer or two. 

Please let me know if you can help.

**Comment by nickreese** [comment]
@lukeed is helping coordinate.

**Comment by sw-yx** [comment]
please take care Nick we need you in good health!! :hugs:

lukeed - i am a happy user but am in a steady state, dont really have any features i want to add right now but if you need me just pull me in - would be a shame to let this proj go to waste.

**Comment by kevmodrome** [comment]
Take care of yourself Nick. Willing to help out in any way I can whenever I have time. ❤️

**Comment by schnubor** [comment]
Hope you'll be ok Nick! Also happy to help whenever I can :)

**Comment by kiuKisas** [comment]
Take care of you Nick ! :heart:   I'll be more active next month

**Comment by polarmutex** [comment]
just started creating my elderjs site, willing to help where needed

thoughts and prayers for you

**Comment by kfrederix** [comment]
Take good care of yourself Nick!!

**Comment by Marcosaurios** [comment]
I just discovered the story behind this framework and I will be starting to use it, and I read this issue... I hope you recover soon Nick!

**Comment by s-kris** [comment]
I just came across this issue. Thank you so much for your work. Take good care of your health.

**Comment by nickreese** [comment]
Out of the hospital. Still getting back on the horse. Doctors say I've got 4-6 months of recovery ahead of me. Thanks to everyone who has jumped in to help. ❤️ 

I've enabled discussions on this repo. Also happy to setup a discord if there is interest though I won't be able to be active in there.

**Comment by nickreese** [comment]
Not 100% back on the grid but it looks like I'm mostly out of the woods health wise. Thanks for all of the support.
