### ISSUE TITLE
Slot doesn't work with hydrate Component

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#139]
As the title said  `slot` doesn't work with hydrate component.
Not sure if it's easy/doable to implement.
Need investigation.
Somewhat related to #137

**Comment by flauc** [comment]
This is actually by design and I believe the actual error message says why. I don't think this will ever be available in elder. However, you can still just hydrate the parent compnent and use `slot` in a child of the hydrated component.

**Comment by kiuKisas** [comment]
Interesting, I'll give a try.
