### ISSUE TITLE
Make Intersection Observer / hydrate-client configurable

### ISSUE THREAD

**Issue by jbmoelker** [Elderjs/elderjs#14]
In some of my use cases the intersection observer used to lazy load components with `hydrate-client` kicked in a bit late. As I understand it @philipp-tailor had a similar issue in #12 in that he'd like components with `hydrate-client` to hydrate instantly.

For these use cases it would be great if the `hydrate-client` behavior would be configurable. I personally like the fact that lazy loading is the default. Maybe the behavior can be extended something like this:
```svelte
<!-- Lazy load component when in view -->
<Component hydrate-client={{}} />

<!-- Hydrate instantly -->
<Component hydrate-client={{}} hydrate-lazy={ false } />

<!-- Lazy load component with specific intersection observer configuration -->
<Component hydrate-client={{}} hydrate-lazy={{ rootMargin: '500px' }} />
```

note: I see [`IntersectionObserver.ts` already accepts a `distancePx`](https://github.com/Elderjs/elderjs/blob/master/src/utils/IntersectionObserver.ts#L3), but it's not accessible from a Svelte template.

**Comment by nickreese** [comment]
Took a stab at this today. Still needs tests written and a plan for preload as it doesn't work with Systemjs because Systemjs is undefined, but here is the WIP PR is here: https://github.com/Elderjs/elderjs/pull/17

**Comment by jbmoelker** [comment]
`hydrate-options=` is a smart solution to not convolute the component's API 💪 

`lazy` is a loading strategy. I would follow the HTML spec here, which supports lazy loading of images and iframes using `<img loading="lazy">` and `<iframe loading="lazy">`.
So combining this with `hydrate-options` would make this `hydrate-options={{ loading: 'lazy' }}`.

**Comment by nickreese** [comment]
@jbmoelker We'll rock "eager" and "lazy" then to match the spec. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading
