### ISSUE TITLE
Enable discussions in Elderjs repositories

### ISSUE THREAD

**Issue by michael0liver** [Elderjs/elderjs#143]
https://docs.github.com/en/discussions/quickstart
I think it would be a better place to ask general questions rather than opening an issue :)

**Comment by kiuKisas** [comment]
Hey @michael0liver , that's a great idea. 
I was considering opening a gitter or something similar,

**Comment by nickreese** [comment]
Enabled discussions here: https://github.com/Elderjs/elderjs/discussions/147

**Comment by michael0liver** [comment]
Thanks 🚀
