### ISSUE TITLE
double prefix route build

### ISSUE THREAD

**Issue by Upsetmania** [Elderjs/elderjs#144]
hi thank you for your engine I find it great for seo, I have a problem with the road I have twice the same prefix on the link
do you have an idea? thank you

![doubleprefixconfig](https://user-images.githubusercontent.com/40160041/110272637-eeb6a280-7fca-11eb-851d-46770ac0ffe7.png)
![doubleprefix](https://user-images.githubusercontent.com/40160041/110272641-ef4f3900-7fca-11eb-984e-03e22d4c9936.png)

**Comment by kiuKisas** [comment]
Hey @Upsetmania ,
This PR: https://github.com/Elderjs/elderjs/pull/134 should fix this issue. I'll have a look tonight if I can merge this one.

**Comment by Upsetmania** [comment]
thank you very much i will wait then;)

**Comment by Upsetmania** [comment]
hi kiKesa yes that's it I'll test thanks for example :)

**Comment by kiuKisas** [comment]
Fix: https://github.com/Elderjs/elderjs/commit/17f70ef57bf594db291c7fe30ae5a059a63f25eb

**Comment by nickreese** [comment]
@Upsetmania Yep, @kiuKisas is working on testing it and bumping deps. We'll ship once that is done. 👍

**Comment by nickreese** [comment]
@Upsetmania released

**Comment by Upsetmania** [comment]
hello, works perfectly thank you;)
