### ISSUE TITLE
 Error: You must supply options.input to rollup

### ISSUE THREAD

**Issue by edjw** [Elderjs/elderjs#146]
I'm getting an error ` Error: You must supply options.input to rollup` 

Using the template `rollup.config.js` with `rollup -c`

Any ideas what could be causing this?

**Comment by jordankaerim** [comment]
I have the same problem. The first build worked. But after deleting all `routes` except `blog` I am seeing this error.

**Comment by jordankaerim** [comment]
I think I found the problem. It happens when all files in the `src/components` directory are deleted. Seems like Elder.js expects at least one Svelte component in that folder.
