### ISSUE TITLE
Body class name route defaults

### ISSUE THREAD

**Issue by Upsetmania** [Elderjs/elderjs#150]
hello to all your engine and great! I am looking for I am looking for but I cannot find the name body class to change I see that the engine imposes the body takes the name of the route how to modify? thank you very much.

![changebody](https://user-images.githubusercontent.com/40160041/110925624-bb09ae80-8323-11eb-9c4b-e0d6ac54f97b.png)

**Comment by kiuKisas** [comment]
This is an auto behavior when you didn't add attributes string, that you can find in `src/hooks/index.ts` in the `compileHtml` hook, line 264
```
      const bodyAttString = bodyAttributesString && bodyAttributesString.length > 0 ? bodyAttributesString : `class="${request.route}"`;

```
So currently, two choices:
- you add a `bodyAttributes` in a `stacks` hook to prevent this behavior. But you have to set something else instead.
- you disable the `elderCompileHtml` hook, and add back a copy of it without this line.

@nickreese I'm not sure why is it here in the first place, I guess we should be able to disable it easier. (even if it's not a priority).

**Comment by Upsetmania** [comment]
ho the second elderCompileHtml empty all html files, how to do the first solution? hooks.js?

**Comment by kiuKisas** [comment]
add this to your `src/hooks.js`:

```
  {
    hook: 'compileHtml',
    name: 'elderCompileHtml',
    description: 'Creates an HTML string out of the Svelte layout and stacks.',
    priority: 50,
    run: async ({
      request,
      settings,
      htmlAttributesString,
      bodyAttributesString,
      headString,
      footerString,
      layoutHtml,
    }) => {
      const htmlAttString =
        htmlAttributesString && htmlAttributesString.length > 0 ? htmlAttributesString : `lang="${settings.lang}"`;
      return {
        htmlString: `<!DOCTYPE html><html ${htmlAttString}><head>${headString}</head><body ${bodyAttributesString}>${layoutHtml}${footerString}</body></html>`,
      };
    },
  },

```

Same as the original but without adding the body class

**Comment by Upsetmania** [comment]
Nice thank you very much works perfectly
