### ISSUE TITLE
Using esbuild 

### ISSUE THREAD

**Issue by s-kris** [Elderjs/elderjs#151]
Any plans of using esbuild to make it even faster?
There's an esbuild-svelte repo already : https://github.com/EMH333/esbuild-svelte

Thank you

**Comment by nickreese** [comment]
https://www.npmjs.com/package/esbuild-svelte

I use this internally but will not be offering any maintenance or movement to it as our Rollup config is incredibly complex and I don't have the appetite to maintain two bundlers.

**Comment by s-kris** [comment]
Fair enough. I'll play with it and see :)
Thanks Nick!!
