### ISSUE TITLE
Non html (json) routes?

### ISSUE THREAD

**Issue by brasilikum** [Elderjs/elderjs#154]
I am thinking about using elder to generate json files for the usecase of listing addresses for zip codes.
Example:

zipcod.es/47593 -> Shows html info about that zipcode
zipcod.es/47593.json -> Returns the same information in json format

Is there a way to achieve this currently with Elderjs?

**Comment by nickreese** [comment]
Yep. Just use one of the hooks and write your desired JSON to a file using a sync `fs` method. Reopen if you hit a snag. Totally doable.
