### ISSUE TITLE
TailwindCSS integration in svelte component `style` tag with `@apply` directive

### ISSUE THREAD

**Issue by jerriclynsjohn** [Elderjs/elderjs#158]
I'm trying to port our sapper-based website into Elder, we use a lot of `@apply` directives in component `<style>` tags. The pre-processor was smart enough to go through every single component style tag and convert all the `@apply`. Is there any solution for this in elder, this is the only thing that is stopping us from using elder for our website now.

**Comment by r6203** [comment]
```@apply``` inside ```<style>``` tags works on my end.  I'm using TailwindCSS JIT (https://github.com/tailwindlabs/tailwindcss-jit).

postcss.config.js:
```
module.exports = {
  plugins: {
    '@tailwindcss/jit': {},
    autoprefixer: {},
  },
};
```

tailwind.config.js:
```
module.exports = {
  purge: ['./src/**/*.svelte'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

**Comment by jerriclynsjohn** [comment]
Oh yes thanks a lot @r6203 I changed my configs to the ones you mentioned above, but now my `npm run build` is stuck indefinitely at `created public\_elderjs\svelte in 1.8s`

**Comment by jerriclynsjohn** [comment]
@r6203 can you let me know if there is any specific setting that I have to follow for production other than NODE_ENV=production

**Comment by jerriclynsjohn** [comment]
Didnt see the `.env` file, changed to production and this works now. Thank you @r6203
