### ISSUE TITLE
How to add `@rollup/plugin-alias` and other rollup plugins

### ISSUE THREAD

**Issue by jerriclynsjohn** [Elderjs/elderjs#159]
How can we add `@rollup/plugin-alias`, how do we add more plugins to the rollup.

**Comment by kiuKisas** [comment]
I don't do that myself and for what is worth, never get into rollup things. As far as I can tell, in your `rollup.config.js`, you should be able to add anything you want to the return of `getRollupConfig({ svelteConfig })`, including plugin used by rollup (you have a `plugins` key which should be what you looking for).

**Comment by nickreese** [comment]
@jerriclynsjohn Currently Elder.js doesn't offer a way to add arbitrary rollup plugins as it will introduce unneeded complexity to the project... but as @kiuKisas alludes you can adjust the output from `getRollupConfig({ svelteConfig })` to add whatever rollup plugins you need. Let us know if you hit snags.

**Comment by jerriclynsjohn** [comment]
Let me try that out and will keep you posted

**Comment by elielr01** [comment]
Hey @jerriclynsjohn !

Did you manage to solve this? I'm also stuck in trying to add this plugin to the rollup configuration object returned by `getRollupConfig`.

However, I haven't been able to make it work. (I'm also not a rollup expert)

So far I have tried something like this:

```javascript
require('dotenv').config()
const alias = require('@rollup/plugin-alias')
const path = require('path')

const { getRollupConfig } = require('@elderjs/elderjs')
const svelteConfig = require('./svelte.config')
const replacements = { preventAssignment: true }

const projectRootDir = path.resolve(__dirname)
const aliasPlugin = alias({
  resolve: ['.svelte', '.js'],
  entries: [{ find: '~', replacement: path.resolve(projectRootDir, 'src') }],
})

const rollupConfigs = getRollupConfig({ svelteConfig, replacements })
rollupConfigs[1].plugins.push(aliasPlugin)
rollupConfigs[2].plugins.push(aliasPlugin)
console.dir(rollupConfigs, { depth: null })

module.exports = [...rollupConfigs]
```
