### ISSUE TITLE
Static images

### ISSUE THREAD

**Issue by DenMesh** [Elderjs/elderjs#16]
The next issue I had may be due to a lack of understanding of how Elder/Svelte works. However, I encouneted a problem while trying to insert a plain static image.

Using the template layout's css as a guide, it seems that I have to either pass the settings object all the way down to the component (which very much rubs me the wrong way) or somehow make it global. Seems a bit overboard for just an image, doesn't it?

**Comment by nickreese** [comment]
@DenMesh A few more details would help here. You should just be able to use an <img> tag in any svelte file.

**Comment by DenMesh** [comment]
Sorry, my bad.

Here is a "M"WE: clone the default template, put a test.jpg file into src/assets. Then open a component (I chose BlogTeaser.svelte) and try to insert an <img> tag.

``<img src="/test.jpg" />`` doesn't work. As expected.
``<img src="/dist/static/test.jpg">`` doesn't work too. Strange, ``style.css`` that shares the folder seems to be loading.

I have restarted both rollup and dev server for good measure *after* moving the test.jpg into the assets folder.

**Comment by nickreese** [comment]
Look in your public folder. If your image isn't there then it isn't getting copied when rollup moves the files from `./src/assets/` to the assets folder defined in your `elder.config.js`. 

Please note this only happens once when you run the rollup command if you are using the template. So if you add new items there you'll need to kill the rollup command and start it again. 

Any file in your /public/ can be accessed via it's relative url. `/public/test.jpg` becomes `/test.jpg`

**Comment by DenMesh** [comment]
Found the reason and the cure.

I was working on a *Windows* machine, so path separators were different. Thus the copy code from rollup config failed. To remedy this replace lines 43 -- 56 in rollup.config.js with the following code (**WARNING**: this code has **not** been tested to any extent other than "it works". Use at your own peril)

```
const assetsPath = path.join(process.cwd(), 'src/assets');
const buildPath = path.join(process.cwd(), locations.assets);
glob.sync(path.resolve(process.cwd(), locations.srcFolder, './assets/**/*')).forEach((file) => {
  const stats = fs.statSync(file);
  const filePath = path.relative(assetsPath, file);
  const destination = path.join(buildPath, filePath);
  const destinationDir = stats.isFile() ? path.dirname(destination) : destination;
  fs.ensureDirSync(destinationDir);
  if(stats.isFile()){
    fs.copyFileSync(file, destination);
  }
});
```

**Comment by nickreese** [comment]
@DenMesh Thanks for circling back with a work around. 👍
