### ISSUE TITLE
Adding a `intl-tel-input` component doesnt work

### ISSUE THREAD

**Issue by jerriclynsjohn** [Elderjs/elderjs#161]
So I've tried this setup using `hydrate-client={{}}` in elderjs and also tried the same in normal svelte project. This works perfectly in svelte project but just wouldn't work in elderjs.

This is what I did.
1. `npm i intl-tel-input`
2. Created a component called `PhoneInput.svelte`
3. Hydrated the component using `hydrate-client={{}}`
4. Throws an error `ReferenceError: self is not defined`

`PhoneInput.svelte`

```svelte
<script>
    import { onDestroy, onMount } from 'svelte';
    import intlTelInput from 'intl-tel-input';
    import 'intl-tel-input/build/js/utils.js';
    import 'intl-tel-input/build/css/intlTelInput.css';

    let phoneNumber, dropdownContainer;

    let iti;
    onMount(() => {
        iti = intlTelInput(phoneNumber, {
            dropdownContainer,
            preferredCountries: ['us', 'hk', 'tw', 'in', 'id', 'br', 'ng', 'jp', 'ru'],
            separateDialCode: true,
            autoPlaceholder: 'aggressive',
            customPlaceholder: function (selectedCountryPlaceholder, selectedCountryData) {
                return 'e.g. ' + selectedCountryPlaceholder;
            },
        });
    });

    onDestroy(() => {
        iti.destroy();
    });
</script>

<input placeholder="Phone number" bind:this={phoneNumber} type="tel" name="phone_number" id="phone_number" />

```

Really don't have a clue about what's happening here.

**Comment by jerriclynsjohn** [comment]
So if I leave out `import 'intl-tel-input/build/js/utils.js';` and `iti.destroy();` then it shows the country dropdown, but the entire `iti` is literally of no use. There is no `destroy` method and most importantly `getNumber` method. Because there is no utils.js the placeholder customization function doesn't work either. The code above works superbly for a normal svelte application.

**Comment by nickreese** [comment]
@jerriclynsjohn It appears your library isn't compatible with SSR. 

Look at wrapping things in a `process.env.componentType === 'browser'` or using a dynamic import for the library in the `onMount` function. 

Useful docs link: https://elderguide.com/tech/elderjs/#understanding-partial-hydration
