### ISSUE TITLE
Example of blog index pagination

### ISSUE THREAD

**Issue by jerriclynsjohn** [Elderjs/elderjs#164]
Hi we are having a huge amount of blogs to list on our website and we want to implement pagination for the index page, Are there any best practices for Elderjs. What direction should I take, is there any plugin that could be used for this. We want a total of 20 blogs to be shown on 1 page and assuming we have more than 200 blogs that would need 10 different pages. Ideally, the route should look like `<domain>/blog/` to `<domain>/blog/10`.

**Comment by timeshift92** [comment]
Hello, if your pageSize is fixed, then you can simply pass the parameter to the permalink
```
 permalink: ({ request }) => `/${request.slug}?page=${request.slug}`,
``

**Comment by jerriclynsjohn** [comment]
> Hello, if your pageSize is fixed, then you can simply pass the parameter to the permalink
> ```
>  permalink: ({ request }) => `/${request.slug}?page=${request.slug}`,
> ``

Won't this result in `blog?page=blog` and yes we have fixed 20 as the number of blogs to be listed per page.

**Comment by timeshift92** [comment]
my bad you need
```
 permalink: ({ request }) => `/${request.slug}?page=${request.currentPage}`,
```

**Comment by apop880** [comment]
Stepping back a level, your `all` object is going to need to go through the count of blog posts and generate a request for each page. Basically, you'd return something like:
```
[{slug: 'blog', page: 0}, {slug: 'blog', page: 1}, ...}]
```
Then, your permalink function would generate a link for each route:
```
if(page === 0) {
   return `/${request.slug}/`;
}
else {
   return `${request.slug}/${request.page}`;
}
```
This will give you `/blog`/, `/blog/1`, `/blog/2`, etc. Then, your `data` section would slice the array of posts based on the page passed in from the request.

Hopefully this helps you get started, I know it's pretty high level. I'm working on something similar for my own website, including tag and month archives with their own pagination. I'm planning to put together a more detailed writeup when it's done.

**Comment by noxasch** [comment]
This is my workaround to get my blog pagination which is kinda hacky

```js
module.exports = {
  template: 'Blog.svelte',
  permalink: ({ request, settings }) => {
    if (request.slug !== 'blog')
      return `/blog/${request.slug}/`;
    if (request.page !== undefined)
      return `/blog/${request.page}`;
    return `/blog`;
  },
  all: async (request) => {
    const postPerPage = 5;
    let pages = Math.floor(request.data.markdown.blog.length / postPerPage);
    let remainder = request.data.markdown.blog.length % postPerPage;
    let slugList = [];
    if (remainder > 0) pages += 1;
    if (pages > 1) {
      for (let i = 0; i < pages; i++) {
        if (i === 0) slugList.push({ 
          slug: 'blog', 
          postStart: 0, 
          postEnd: postPerPage, 
          isLastPage: i === pages - 1,
          lastPage: pages,
          template: 'BlogIndex' });
        else slugList.push({ 
          slug: 'blog', 
          page: i, 
          postStart: i * postPerPage, 
          postEnd: (i * postPerPage) + postPerPage,
          isLastPage: i === pages - 1,
          lastPage: pages,
          template: 'BlogIndex' 
        });
      }
    }
    return slugList;
  },
  data: {},
};

```

And in my BlogIndex.svelte

```html
<script>
  export let data, request, helpers;
  let blogPost = data.markdown.blog.slice(request.postStart, request.postEnd);
</script>
```

And for pagination

```html
<script>
  export let request, helpers;
  let prevPage;
</script>

<div class="pagination">
    {#if request.page !== undefined && parseInt(request.page) - 1 !== 0}
      <a href="{helpers.permalinks.blog({ slug: 'blog', page: parseInt(request.page) - 1,})}" class="prev">&lsaquo;</a>
    {:else if parseInt(request.page) - 1 === 0}
      <a href="{helpers.permalinks.blog({ slug: 'blog'})}" class="prev">&lsaquo;</a>
    {/if}
    Page {#if request.page === undefined} 1 {:else} {parseInt(request.page) + 1} {/if} / {request.lastPage}
    {#if !request.isLastPage && request.page !== undefined}
      <a href="{helpers.permalinks.blog({ slug: 'blog', page: parseInt(request.page) + 1})}" class="next">&rsaquo;</a>
    {:else}
      <a href="{helpers.permalinks.blog({ slug: 'blog', page: 1})}" class="next">&rsaquo;</a>
    {/if}
</div>
```
