### ISSUE TITLE
docs: document difference to sveltekit?

### ISSUE THREAD

**Issue by sw-yx** [Elderjs/elderjs#171]
from the HN thread today, lots of folks asking about the difference vs Sveltekit: https://news.ycombinator.com/item?id=27153319

wondering if its worth documenting this up front to answer the question? since i imagine it will be a popular one. happy to send pr if yes

**Comment by nickreese** [comment]
100% open to this and will contribute as well. Haven’t been a big user of SvelteKit so would love input from someone more familiar. 👍

**Comment by sw-yx** [comment]
i just realized its over in this repo so i will move this issue https://github.com/Elderjs/docs/blob/master/elderguide.com/elderjs.md
