### ISSUE TITLE
Thumbs up ! And file name for route using .md should use '-' not spacebar

### ISSUE THREAD

**Issue by x4080** [Elderjs/elderjs#18]
Hi, I just drop in to say very cool tool to create blog style website, love it!

I just found that file .md must use '-' as filename (I use space bar between word and cannot found the route)

Thanks for this invention

**Comment by nickreese** [comment]
@x4080 try updating the plugin included with the test template with below. 

On line 34 in ./src/plugins/elderjs-plugin-markdown/index.js

```javascript
          let fileSlug = file.replace('.md', '').split('/').pop();

          if (fileSlug.includes(' ')) {
            fileSlug = fileSlug.replace(/ /gim, '-');
          }
```

I'll update the template.

**Comment by nickreese** [comment]
@x4080 Let me know if this doesn't fix it for ya. I've updated the template.

**Comment by x4080** [comment]
@nickreese Wow, very fast response - thanks. I just stumble on it while trying your cool project. And its ok for me not using spacebar. But thanks for your update, really appreciate it

**Comment by x4080** [comment]
And its working for space bar now, thanks

**Comment by x4080** [comment]
@nickreese Early stats, moving from sapper to elderjs 

Sapper build time : 
```
> Finished in 24.5s. Type node __sapper__/build to run the app.
```

Elderjs build time :
```
Build completed 28 pages in 964ms
```

Sapper Pagespeed insights : 92,97 (mobile,desktop)
Elderjs Pagespeed insights : 97,97 (mobile,desktop)

Very cool
