### ISSUE TITLE
Can not mutate request object from middleware hook anymore (v1.4.5)

### ISSUE THREAD

**Issue by bbuhler** [Elderjs/elderjs#186]
Hello again 👋🏼 

Since I updated to 1.4.5 some of my hooks are throwing errors about missing properties in request object. It seems like that properties set and returned by 'middleware' hooks are not available in e.g. 'stacks' hooks anymore.

```js
  {
    hook: 'middleware',
    name: 'testMiddleware',
    description: 'Test middleware',
    run({ request })
    {
      request.test = true;

      return { request };
    },
  },

  {
    hook: 'stacks',
    name: 'testStacks',
    description: 'Test stacks',
    run({ request })
    {
      console.log(request.test); // undefined
    }
  },
```

**Comment by nickreese** [comment]
@bbuhler thanks! had an issue where the request from earlier hooks wasn't getting passed through the default router.  Should be resolved in v1.4.6.
