### ISSUE TITLE
Question : not using service worker ?

### ISSUE THREAD

**Issue by x4080** [Elderjs/elderjs#19]
Hi, is elderjs not using service worker ? Or dont need it ?

Thanks

**Comment by nickreese** [comment]
@x4080 No service worker needed at this time. They are complex to debug and are we didn't see any advantages for the SSG to include it... but we're open to having our minds changed if there is a large oversight on our end. 👍 

What problem would the service worker solve? Just looking for offline support?

**Comment by x4080** [comment]
@nickreese, thanks for quick reply, I agree with quirks with service worker, I experienced strange things using sapper with sw, like when I refresh the page (mainly in IOS) - some components will appear twice

I just think using service worker for static assets for first loading - it will improve page loading, and lighthouse score :)

Not thinking about offline right now

**Comment by jbmoelker** [comment]
Hi @x4080, you can do caching of static assets without a Service Worker using cache headers. For example in the [Elder.js template](https://github.com/Elderjs/template) the Svelte components are compiled to `/public/dist/svelte/`. The filenames contain a hash like `entryClock-075a8898.js`. The hash ensures the name changes as the file contents change. So you can set a cache header to `Cache-Control: public, max-age=31536000, immutable`.

If you use Netlify for instance you could achieve this using:
```
# netlify.toml
[build]
  command = "yarn build"
  publish = "public/"

[[headers]]
  for = "/dist/svelte/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
```

**Comment by x4080** [comment]
@jbmoelker Thanks for the tip

**Comment by nickreese** [comment]
@jbmoelker Included this in the netlify.toml of the template. We were doing this on our Cloudflare worker on ElderGuide.com but hadn't documented it for Netlify. This is a great addition.

**Comment by x4080** [comment]
@nickreese I'm playing with firebase hosting here's for firebase.json

```
{
  "hosting": {
    "public": "public",
    "headers": [
      {
        "source": "/**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache, no-store, must-revalidate"
          }
        ]
      },
      {
        "source":
          "**/*.@(jpg|jpeg|gif|png|svg|webp|js|css|eot|otf|ttf|ttc|woff|woff2|font.css)",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "max-age=31536000"
          }
        ]
      }
    ],
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}

```
