### ISSUE TITLE
Possibility to change layout from hooks

### ISSUE THREAD

**Issue by bbuhler** [Elderjs/elderjs#193]
Hello 👋🏼 

We want to AB test two different layouts. Is it possible to change the layout component for a request from hooks?

If yes, how?
If no, can you think of another possible solution?

<details>
<summary>
I tried having a wrapper component as layout which then imports both variants and renders based on data property, but then the embedded CSS contains styles from both variants.
</summary>

```svelte
<script>
  import VariantA from './VariantA.svelte';
  import VariantB from './VariantB.svelte';

  export let data;
</script>

{#if data.variant === 'B'}
  <VariantB {...$$props} />
{:else}
  <VariantA {...$$props} />
{/if}

```

</details>

Also this way I can not use partial hydration.

Thanks in advance.

**Comment by nickreese** [comment]
@bbuhler It would be a bit hacky, but the quickest way is to setup another route that uses the layout you want. Then on the `request` object adjust the `route` name to match the other layout via a hook where it is mutable. 

At some point I'd like to refactor Elder.js to manage the route/layout component information on the route itself, but it has wide reaching implications for plugins and hooks in general. Referencing a stable `routes` object is absolutely key for plugins, esp if a plugin offers a theme.

**Comment by bbuhler** [comment]
Thank you, I will that.
