### ISSUE TITLE
Props in shortcode are passed as an Array instead of Object

### ISSUE THREAD

**Issue by NoelOConnell** [Elderjs/elderjs#209]
When trying to create a shortcode for our site I noticed an issue with the props argument received in the shortcode run function.

I cloned and ran the Elderjs template project to make sure our configuration was not causing the issue.

**Steps to reproduce**
- Clone the Elderjs template
- Edit the `getting-started.md` and add the `box` shortcode that is shown in the documentation page.
```
{{box type="gray"}}
  Your content here
{{/box}}
```

Expected output of props in the shortcode function
`{ type: "gray" }`

Actual
`[ type: 'gray' ]`

![image](https://user-images.githubusercontent.com/966495/132881541-1e5b5da3-86f2-40af-a1cc-8de9d7312235.png)
![image](https://user-images.githubusercontent.com/966495/132881598-8560c047-1730-44d5-992b-edb2e59b8307.png)

**Comment by nickreese** [comment]
Hi, thanks for this. So I can try and recreate, can you let me know your output of `npx envinfo --system --npmPackages svelte,rollup,webpack --binaries`? Thanks

**Comment by NoelOConnell** [comment]
Sure, here's the output
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 20.58 GB / 31.92 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD      
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    rollup: ^2.41.1 => 2.47.0 
    svelte: ^3.38.3 => 3.38.3 
```

**Comment by nickreese** [comment]
Turns out this was a legacy issue with the forked https://github.com/elderjs/shortcodes. I've updated it to always return an object. It is part of the latest release of Elder.js.
