### ISSUE TITLE
Enhancement: preload System.js

### ISSUE THREAD

**Issue by jbmoelker** [Elderjs/elderjs#21]
I understand the usage of System.js is an ongoing discussion (#12). But as long as it's in, maybe it's smart to preload it. This ensures components can hydrate more quickly. I'm currently doing this using a custom hook, but I imagine this could be an internal hook:

```js
// src/hooks.js
module.exports = [{
  hook: 'stacks',
  name: 'preloadSystemJs',
  description: 'add link[rel="preload"] for System.js script',
  priority: 50,
  run: ({ headStack, settings }) => {
    const preloadLink = {
      source: 'hooks:preloadFonts',
      string: `<link rel="preload" href="${settings.locations.systemJs}" as="script">`,
    };
    return {
      headStack: [...headStack, preloadLink],
    };
  },
}];
```

**Comment by jbmoelker** [comment]
Alternatively I could bundle this into a community plugin for preloading. As I'm using a similar hook to preload fonts:
```js
// src/hooks.js
module.exports = [{
  hook: 'stacks',
  name: 'preloadFonts',
  description: 'add link[rel="preload"] for all *.woff2 files',
  priority: 50,
  run: ({ cssStack, headStack }) => {
    const woff2pattern = /url\(["'](.*)["']\)\s+format\(["']woff2["']\)/;
    const woff2urls = cssStack
      .map((css) => css.string.split(';'))
      .flat()
      .map((line) => {
        const match = line.match(woff2pattern);
        return match ? match[1] : false;
      })
      .filter(Boolean);

    const preloadLinks = {
      source: 'hooks:preloadFonts',
      string: woff2urls
        .map((woff2url) => `<link rel="preload" href="${woff2url}" as="font" type="font/woff2" crossorigin>`)
        .join(''),
    };

    return {
      headStack: [...headStack, preloadLinks],
    };
  },
}];
```

**Comment by nickreese** [comment]
@jbmoelker Great idea. We'll get preloading in there by default in one of the next releases. I'd love your thoughts on ESM/Systemjs as well if you have any bandwidth to think on it. 

One note, we need to investigate how stacks are handled if a priority isn't given.

**Comment by nickreese** [comment]
@jbmoelker Pushed in 0.0.24. Going to work on getting a full tagging/changelog process moved over shortly. I know @halafi was looking at one last week.
