### ISSUE TITLE
Html being sanitized from markdown

### ISSUE THREAD

**Issue by conoroshea1996** [Elderjs/elderjs#213]
Hello I ran into and issue using the lastest packages from elderjs.
This is current  package vesions
![Capture](https://user-images.githubusercontent.com/47694309/134724625-5b34c911-7296-4933-8330-64c17134ae6e.PNG)

It seems as though any html from markdown is being removed 
- Use case is I want to use a html table inside a markdown file 

I digged abit deeper and found that if I set  sanitize to false in the markdown plugin it no longer parses out the html
  https://github.com/remarkjs/remark-html#optionssanitize

This is the change I made to prevent the html being parsed out from a markdown file. 
But Im not too sure if this is a good way to solve this issue.
(Index.js markdown plugin)
![Capture](https://user-images.githubusercontent.com/47694309/134725195-d4f4a8ae-9d4f-41fc-a322-a01729d439a5.PNG)

**Comment by nickreese** [comment]
@conoroshea1996 Thanks for this. I had been troubleshooting #214 and hadn't realized `remarkHtml` had changed it's api. Fixed in latest plugins.
