### ISSUE TITLE
Question : How to make html component/svelte component work inside .md ?

### ISSUE THREAD

**Issue by x4080** [Elderjs/elderjs#22]
Hi, I'm using html component inside .md and interactivity is not working (not mounted ?) - Is there a way to make it "mount", using like  hydrate-client={{}} ?

Thanks

P.S Even better if we can use svelte component directly ala MDsvex

**Comment by nickreese** [comment]
Currently there is no officially supported way but I imagine you could use html that matches the regex for hydration in `svelteComponent.ts`

I’ve never gone too far down the MDsvex rabbithole. If you see a way we could integrate jt let me know.

**Comment by x4080** [comment]
@nickreese Right now, i do workaround by using svelte component (BlogContainer) inside Blog.svelte example :
```
<BlogContainer hydrate-client={{post:_post}} />
```

And using web components, but it makes it like sapper, the benefit is quickly build posts by using elderjs tech

Hope it helps somebody

**Comment by nickreese** [comment]
@x4080 In v0.1.2 We released `helpers.inlineSvelteComponent(name, props, options)` which will output the html needed to hydrate the components. The markdown must be preprocessed before it gets to the layout processing in `page.ts`

**Comment by x4080** [comment]
@nickreese Cool, I'll check it out

**Comment by vchirikov** [comment]
@nickreese could you provide an example with mdsvex?
