### ISSUE TITLE
Empty css variables rendered invalid on build

### ISSUE THREAD

**Issue by dmlayton** [Elderjs/elderjs#229]
I'm using tailwind and upon `build` I get `var(--tw-empty,)` in my css instead of `var(--tw-empty, )` whihc is valid and what I get in `dev`.

There is a discussion of the issue in general [here](https://github.com/tailwindlabs/tailwindcss/issues/2889). 

I can't work out why this is happening in `npm run build` but not `npm run dev`. I assume it is in the css minification.

**Comment by nickreese** [comment]
@dmlayton CSS minificaiton is more aggressive on production builds. Unfortunately at the moment there is no way to override this behavior.
