### ISSUE TITLE
Question : how to get dynamic .md specific to routes

### ISSUE THREAD

**Issue by x4080** [Elderjs/elderjs#23]
Hi, in the template example, the .md is put inside blog folder/route, I duplicate it to for example blog2, 
I can get all hook up easily with changing @elder.config.js and all markdown data is automatically inside data.markdown in Home.svelte

However, the markdown is centralized (all markdowns from /blog and /blog2 is in data.markdown)

The question, how to split the markdown data, should we use frontmatter data to add route info ? Or there's already solution with it ?

Thanks

**Comment by nickreese** [comment]
@x4080 This is done automatically for the blog routes.

See this: https://github.com/Elderjs/template/blob/5bf46064ba3dc44e8b0d26d6482100aa624d9102/src/plugins/elderjs-plugin-markdown/index.js#L85

`data.markdown` includes all of the parsed files. You can look it up by the slug. Parsed frontmatter is under the `data` key for each parsed markdown.

**Comment by x4080** [comment]
@nickreese Thanks for answering, what I meant is the reverse, I wanted to get all the markdown url for the blog2 folder only, so I must add information to frontmatter data, to do the filtering from markdown data ?

Thanks, and sorry if I'm not clear before

**Comment by nickreese** [comment]
@x4080 No easy way to do that with the minimal example plugin that is included with the template. You could modify that plugin to do so though.

**Comment by x4080** [comment]
@nickreese Thanks
