### ISSUE TITLE
Consider Unpublishing nickreese/elderjs from npm registry?

### ISSUE THREAD

**Issue by nat42** [Elderjs/elderjs#250]
When searching www.npmjs.com for "elderjs" the top result (due to being an "exact match") is [nickreese/elderjs](https://github.com/nickreese/elderjs) ie. 3 files that haven't been changed in 2 years, where the javascript just prints "This is a placeholder" to the console, and the total size of all the files is less than 1KB.

Noticing this I thought I'd suggest considering unregistering / unpublishing this package from the npm registry to avoid this issue.

I don't think it's much of a problem, and I don't even know if it's fooled anyone before (I would have likely followed the directions in the online docs to discover the package, and was just searching around on npm registry website on this occasion as it gave a quick answer to something I was curious about) but I perhaps it might be a minor annoyance to someone and it possibly is somewhat ironic for the proper version of the SEO first framework to not be the top result on the major package registry's search engine.

![image](https://user-images.githubusercontent.com/24620474/181193175-661888e8-384c-4db5-81db-531366d5806f.png)

**Comment by nickreese** [comment]
@nat42 done.
