### ISSUE TITLE
Error with NPM START

### ISSUE THREAD

**Issue by arjarn** [Elderjs/elderjs#26]
Hi and thanx for your great work 👍

I'm attempt using your template with windows platform.
All is right except when I'm doing "NPM START".
Having this error :

    elderjs-template@1.0.0 start E:\elderjs-app
    npm run build:rollup && npm run dev:server

    elderjs-template@1.0.0 build:rollup E:\elderjs-app
    rollup -c

rollup production === true. Because watch is undefined.

./node_modules/intersection-observer/intersection-observer.js → public\dist\static\intersection-observer.js...
created public\dist\static\intersection-observer.js in 1.4s

./node_modules/systemjs/dist/s.min.js → public\dist\static\s.min.js...
created public\dist\static\s.min.js in 1.3s

./src/routes/blog/Blog.svelte → ./ELDER/compiled/...
[!] (plugin svelte) TypeError: content.matchAll(...) is not a function or its return value is not iterable
src\routes\blog\Blog.svelte
TypeError: content.matchAll(...) is not a function or its return value is not iterable
at markup (E:\elderjs-app\node_modules@elderjs\elderjs\build\partialHydration\partialHydration.js:21:37)
at preprocess (E:\elderjs-app\node_modules\svelte\src\compiler\preprocess\index.ts:86:27)

**Comment by nickreese** [comment]
@arjarn node v12+ is required. Try upgrading it should work.

**Comment by arjarn** [comment]
Argh, I'm too bad...

All is ok after upgrading 👍 

Thanx.
