### ISSUE TITLE
Configure elderjs-plugin-browser-reload

### ISSUE THREAD

**Issue by mosheduminer** [Elderjs/elderjs#32]
Hi, I realized today that elderjs-plugin-browser-reload, uses port 8080 for reloading. I would like to be able to configure the port used, as I have a service running on port 8080, and it would be convenient to not need to change it 😄.
Thanks for the great framework!

**Comment by nickreese** [comment]
Details here: https://github.com/Elderjs/plugins/tree/master/packages/browser-reload

Let me know if you hit snags.
