### ISSUE TITLE
Proposal: Out-of-the-box support for Closure Compiler

### ISSUE THREAD

**Issue by kevmodrome** [Elderjs/elderjs#33]
Recently came across this cool project from Google called [Closure Compiler](https://developers.google.com/closure/compiler). From some testing it seems like it reduces code size quite a bit, an example that was [recently posted on the svelte subreddit](https://www.syntaxsuccess.com/viewarticle/optimizing-svelte-applications) shows some pretty significant gains (from 1.3 to 0.8 time to interactive and a much smaller bundle size).

**Comment by kevmodrome** [comment]
There's also a [Rollup plugin](https://github.com/ampproject/rollup-plugin-closure-compiler) for it.

**Comment by kevmodrome** [comment]
After some tests on elderguide.com scripts it doesn't look like there's much benefit. Might be worth investigating more, though.

**Comment by nickreese** [comment]
@kevmodrome Tested this out when working on #42. It crashes mysteriously with any non-trivial implementation. 

On the trivial implementations, almost no size benefit.
