### ISSUE TITLE
Proposal: ensure slashes in permalink function output

### ISSUE THREAD

**Issue by DenMesh** [Elderjs/elderjs#40]
At present a route fails if its permalink does **not** start **or** end with a slash. For example, ``/foo/bar/`` works, ``foo/bar/`` fails, ``/foo/bar`` also fails. This creates a manageable but annoying amount of repeating code if there is an optional first path segment in the route: `/${part1}/${part2}/` creates a double slash if part1 is undefined. I propose adding a bit of post-processing to the permalink to **ensure** that it starts **and** ends with a slash (basically, "if not starts with slash, add slash; if not ends with slash, add slash")

**Comment by nickreese** [comment]
@DenMesh will be fixed in v1.0.1 which is shipping shortly.

**Comment by nickreese** [comment]
Permalinks will always have a beginning/trailing slash. 

We'll now throw when having "//" and will warn for "/undefined/" and "/null/".
