### ISSUE TITLE
Adding a base href

### ISSUE THREAD

**Issue by JanMalch** [Elderjs/elderjs#43]
How can I add a custom base URL to the exported files, like [Sapper's Base URLs](https://sapper.svelte.dev/docs#Base_URLs)?
Even when I add it manually, it doesn't work because e.g. the `style.css` link has a leading slash. Thanks in advance.

**Comment by nickreese** [comment]
You’re interested in the `server.prefix` In your `elder.config.js`  The default template will still serve the assets from the folder defined as you `distDir`.

Look for the full `elder.config.js` Spec here: https://elderguide.com/tech/elderjs/#specifications-and-config

**Comment by JanMalch** [comment]
Ah I missed that.
I set it to '/test/' but when I run `npm run build` the link is still `/style.css`.
For context: I would like to use it for a GitHub Page, so I have no control over the server behaviour and the page won't be at the root but for some repository.

**Comment by nickreese** [comment]
@JanMalch Ah, OK. In that case you're looking at adjusting your `distDir` that will control where the files are placed during build. The `server.prefix` only adds it to all of the permalinks in `server`.

**Comment by JanMalch** [comment]
I have that aswell

```js
  distDir: 'public' + BASE_PATH,
  rootDir: process.cwd(),
  build: {},
  server: {
    prefix: BASE_PATH,
  },
```

but it's still the same.
I mean it's in the correct directory but when I deploy the public/test directory for the "test" repository, it will find the index.html at https://janmalch.github.io/test it but the `/styles.css` will be searched for at https://janmalch.github.io/styles.css and not https://janmalch.github.io/test/styles.css

**Comment by nickreese** [comment]
Assuming you're using the template try editing your Layout.svelte to be:

```
<script>
  export let routeHtml, settings;
  const stylePath = settings.distDir + '/style.css';
</script>

<style>
  :global(h1) {
    font-style: italic;
  }
  .container {
    max-width: 900px;
    margin: 0 auto;
    padding: 1rem;
  }

  :root {
    --balloon-color: #06395a;
    --balloon-font-size: 14px;
  }
</style>

<svelte:head>
  <link rel="stylesheet" href={stylePath} />
  <link rel="stylesheet" href="https://unpkg.com/balloon-css/balloon.min.css" />
</svelte:head>
<div class="container">
  {@html routeHtml}
</div>

```

**Comment by JanMalch** [comment]
What about the `<link rel="preload" href="/static/s.min.js" as="script">` that isn't part of the Layout component?

**Comment by nickreese** [comment]
@JanMalch That is a bug. Thanks. Those should be relative to the `distDir` thank you.

**Comment by nickreese** [comment]
Actually thinking on this, the `distDir` really should always be the root of the site. We're almost looking at something different similar to the `server.prefix` setting. 

I need to think on how this would be implemented. 

To unblock you: 

1. Add 'elderAddDefaultIntersectionObserver' and 'elderAddSystemJs' to your `hooks.disable` array in your `elder.config.js`
2. Add these to you hooks.js

```javascript
   {
    hook: 'stacks',
    name: 'customElderAddDefaultIntersectionObserver',
    description: 'Sets up the default polyfill for the intersection observer',
    priority: 100,
    run: async ({ beforeHydrateStack }) => {
      return {
        beforeHydrateStack: [
          {
            source: 'elderAddDefaultIntersectionObserver',
            string: `<script type="text/javascript">
      if (!('IntersectionObserver' in window)) {
          var script = document.createElement("script");
          script.src = "/test/static/intersection-observer.js";
          document.getElementsByTagName('head')[0].appendChild(script);
      };
      </script>`,
            priority: 100,
          },
          ...beforeHydrateStack,
        ],
      };
    },
  },
  {
    hook: 'stacks',
    name: 'customElderAddSystemJs',
    description: 'AddsSystemJs to beforeHydrateStack also add preloading of systemjs to the headStack.',
    priority: 1,
    run: async ({ beforeHydrateStack, headStack }) => {
      return {
        beforeHydrateStack: [
          {
            source: 'elderAddSystemJs',
            string: `<script src="/test/static/s.min.js"></script>`,
            priority: 99,
          },
          ...beforeHydrateStack,
        ],

        headStack: [
          {
            source: 'elderAddSystemJs',
            string: `<link rel="preload" href="/test/static/s.min.js" as="script">`,
            priority: 99,
          },
          ...headStack,
        ],
      };
    },
  },
```

**Comment by JanMalch** [comment]
Thanks for the help, I will try them asap.

Couldn't you just remove the leading slashes and add an option for a `<base href>` tag?

**Comment by nickreese** [comment]
That may work, I just want time to test it and think of the tradeoffs of various implementations. That reality is that `server.prefix` and `build.prefix` being added to these is probably the ideal outcome. 

For instance if you have `/dev` As your prefix the `/static/` folder is still read from the `/public/static/` in the default template because `sirv` is only watching the `/public/` folder and this causes some issues. 

Serving of static assets in the `distDir` With a prefix may require sirv to live in the Elder.js core which is a big change.

**Comment by nickreese** [comment]
Going to close this for inactivity.

**Comment by jnv** [comment]
Hi, I'm going to bump this issue. A typical use case which (I think) is related to this is deploying the site to GitHub or GitLab Pages. It seems to me Elder.js doesn't quite support this use case yet...?

**Comment by nickreese** [comment]
@jnv I think I don’t fully follow the issue. With v1.2.1 css is now added automatically by elderjs. 

The idea is that there is a need for a prefix within the distDir?
