### ISSUE TITLE
Proposal: Consolidate `${distDir}/static/` and `${distDir}/svelte/ into `${distDir}/_elder/`

### ISSUE THREAD

**Issue by nickreese** [Elderjs/elderjs#46]
Consolidating the folder structure output to the `distDir` will allow for aggressive caching by users and allow us to add an arbitrary number of folders under it as long as all files are hashed.

Outline of Change:
1. Add a hash to all rollup bundles as we do in production.
1. Change where svelte components are output. 
1. Change where polyfills are output.
1. Modify `Elder.ts` to find hashed polyfills.
1. Update polyfill hook to use the hashed files. 

Brought up @jbmoelker in #45.

**Comment by sw-yx** [comment]
i like it. also reduces chance of name clash.

**Comment by nickreese** [comment]
PR for this.
