### ISSUE TITLE
Error: Client side hydrated component includes client side hydrated sub component.

### ISSUE THREAD

**Issue by f-elix** [Elderjs/elderjs#49]
Hi! 

First of all, thank you so much for you and your team's work. Elderjs looks really powerful and is a much needed addition to the Svelte ecosystem.

I'm trying to port a Sapper site to Elderjs and I'm running into the issue of having reactive sub-components not being supported (By reactive, I mean client-side hydrated, in order to use Svelte's reactivity features).

To be clearer, I'm trying to do something like:

```
// Page.svelte
<script>
import Reactive from '@/components/Reactive.svelte';

export let data;
</script>

<Reactive hydrate-client={{ data }} />
```

And then in the Reactive.svelte file:

```
// Reactive.svelte
<script>
import SubReactive from '@/components/SubReactive.svelte';

export let data;
</script>

<SubReactive {data.releventData} />
```

I have several nested components like this, but only the top one has the "hydrate-client" prop. Yet I'm still getting the error message from this issue's title.

Am I doing something wrong or is this really impossible in Elderjs?

**Comment by nickreese** [comment]
@f-elix the above example should work as rollup will bundle them together. Try killing rollup and starting again. 

What isn’t supported is two `hydrate-client={{ data }} ` in a tree but that is a Svelte limitation as both would be trying to manage the same part of the dom and they’ll break.  

That said, if restarting rollup, doesnt work look across your component imports to see if you find two `hydrate-client={{ data }}` in a tree.

**Comment by nickreese** [comment]
To be clear I’m not saying there isn’t a bug but `svelteComponent` Is a recursive function that only recurses when it find a component that needs to be hydrated and it should only throw that error when it recurses  while it is already hydrating. 

Only other edge cases is possibly using a `helper` to mount a svelte component inline.

**Comment by nickreese** [comment]
@f-elix also check your layout and route svelte files as they may also have the hydrate code in them but may be missed when staring at the components folder.  :)

**Comment by f-elix** [comment]
Hey thanks for the quick response!

So in VSCode I can do a global search in the folder, and I really see "hydrate-client" on only one component right now (and no "hydrate-options" for that matter), in a route's Svelte file. 

Also, if by killing rollup you mean ctrl+c, yes I've been doing that several times. Is there something else I should do?

I just copy/pasted all my component files from the original project, which are using a lot of Svelte features. Maybe some of them are causing problems? The Context API, <svelte:window />, <svelte:head />, <svelte:component />, for example?

**Comment by nickreese** [comment]
@f-elix can you create a repo with a reproduction. I can't recreate the issue. 

* `<svelte:head/>` shouldnt be an issue as this is returned during rendering and we use it all the time.
* `<svelte:window>` I'm not sure and will need to look more into this as we don't use it often.
* `<svelte:component>` we use this often as well. 

If it isn't too much work, can you open up `node_modules/@elderjs/elderjs/build/utils/svelteComponent.js` in your project and change lines 71-73 to:

```
      if (hydrateOptions) {
        console.error(
          `Client side hydrated component "${componentName}" includes client side hydrated sub component "${hydrateComponentName}." This isn't supported.`,
        );
      }
```

and report back with what the console error was along with what component mount HTML was produced?

(Next release of Elder.js will have a better error there).

**Comment by f-elix** [comment]
Ok that debugging log was actually very useful!

I no longer have this error. My guess is that the problem was with the naming of the components. It might be worth looking into it.

I have a `Page.svelte` **route template** that imports a `Page.svelte` **component** (which has the hydrate-client prop). A soon as I renamed my component to something else, the error went away. I thought both files having the same name would be ok since they are not in the same folder, but apparently this was the problem.

Unfortunately I can't say with 100% certainty that the problem is resolved because even though I can now see the rendered site, the javascript (and all reactivity) fails due to, I think, other errors between Elderjs and my code that I don't know how to fix yet (for example, accessing process.env inside my components is not possible right now). 

I'll try to get everything working on my side during the weekend, or at least get rid of any errors, and get back to you.

**Comment by nickreese** [comment]
@f-elix Ah yep, naming conflicts is on the to-do list: #41 . 

If you are struggling with Svelte directives (bind:foo, use:foo), it is helpful to realize that `hydrate-client={{}}` is literally just a wrapper around the Svelte mount code so those aren't supported **during hydration** by Svelte so we can't support them.

Instead, just create a `<ThingWrapper>` component and hydrate that. Everything should work as expected. 

Doesn't work:

```html
<!-- Home.Svelte -->
<script>
  export let data;
  import AutoComplete from 'simple-svelte-autocomplete';
</script>
<CompanyFinder hydrate-client={{ items: data, bind: bind:selectedItem={selected}, labelFieldName:"NAME" }} />
```
----

Works:


```html
<!-- AutoCompleteWrapper.Svelte -->
<script>
  import AutoComplete from 'simple-svelte-autocomplete';
  export let data;

  let selected;

</script>

<AutoComplete items={data} bind:selectedItem={selected} labelFieldName="NAME" />
```

```html
<!-- Home.Svelte -->
<script>
  export let data;
  import AutoCompleteWrapper from '../../components/AutoCompleteWrapper.svelte';

</script>
<AutoCompleteWrapper hydrate-client={{ data }} />
```


-------

Under the covers Elder.js is inserting one of these every time you use `hydrate-client`:

```javascript
const component = new Foo({
	target: //unique id here,
	props:  // hydrate-client props here
});
```

**Comment by f-elix** [comment]
@nickreese All right I got most things working, at least without getting any errors, so I can now confirm that it was definitely the naming problem that was causing the error. The Svelte directives weren't a problem for me, but that's still good to know. 

With that resolved, I'm going to close the issue.

Thank you so much for your help!
