### ISSUE TITLE
\n being stripped out by overly greedy regex. 

### ISSUE THREAD

**Issue by myrsmedenstorytel** [Elderjs/elderjs#51]
I am experiencing some issues with Client Hydration of external Svelte components.
When putting a component inside the components folder it is working well, but if I import my component from a package inside node_modules, I get the following error:

```
[
  Error: Cannot find module '**DIR**/___ELDER___/compiled/Button.js'
  Require stack:
  - **DIR**/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js
  - **DIR**/node_modules/@elderjs/elderjs/build/utils/index.js
  - **DIR**/node_modules/@elderjs/elderjs/build/routes/routes.js
  - **DIR**/node_modules/@elderjs/elderjs/build/Elder.js
  - **DIR**/node_modules/@elderjs/elderjs/build/index.js
  - **DIR**/src/server.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
      at Function.Module._load (internal/modules/cjs/loader.js:835:27)
      at Module.require (internal/modules/cjs/loader.js:1012:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at **DIR**/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js:38:28
      at Object.templateComponent (**DIR**/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js:74:71)
      at buildPage (**DIR**/node_modules/@elderjs/elderjs/build/utils/Page.js:41:40)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Object.run (**DIR**/node_modules/@elderjs/elderjs/build/hooks.js:81:34)
      at async **DIR**/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:45:44 {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '**DIR**/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js',
      '**DIR**/node_modules/@elderjs/elderjs/build/utils/index.js',
      '**DIR**/node_modules/@elderjs/elderjs/build/routes/routes.js',
      '**DIR**/node_modules/@elderjs/elderjs/build/Elder.js',
      '**DIR**/node_modules/@elderjs/elderjs/build/index.js',
      '**DIR**/src/server.js'
    ]
  }
]
```

I am trying with importing this `Button` component.
From what I can see, we only get compiled versions of things inside our `src` directory and not the external resources. However, without the client hydration, it is working well (except for the hydration part then). 

```
<Button type="secondary" />
```
This renders fine, but with the `hydrate-client` property we get this error above.
```
<Button hydrate-client={{ type: 'secondary' }} />
```

My initial thought is that we must include the external library in our rollup config so that it is compiled as well. We have followed the instructions [here](https://github.com/sveltejs/rollup-plugin-svelte) and have the `svelte` property in our `package.json`. It works well with Sapper. Any ideas on how we can proceed?

**Comment by nickreese** [comment]
@myrsmedenstorytel Elder.js needs to bundle all of the individual components for hydration. Since it isn’t looking in the `node_modules` folder it isn’t bundling the button. We could add this option but with large UI libraries with lots of components the dev experience would be horrendously slow bundling lots of components. 

Try this: wrap the external component that you want to hydrate in a new component that lives in your components folder. This will cause it to get bundled. 

Another option is copying the other component out of the `node_modules` folder into your project. 

With Elder.js I’ve found it is better to hydrate larger groups of components instead of many individual components. So instead of hydrating 3 buttons in the nav, just hydrate the nav.

**Comment by nickreese** [comment]
Note. You make have to kill your `nom run dev:rollup` To get it to rebundle.

**Comment by nickreese** [comment]
Thinking more on this We could add an option to specify arbitrary files to SSR in your rollup config.

**Comment by myrsmedenstorytel** [comment]
Thank you for your quick replies! It would be really nice to be able to specify some files in the rollup config. 
It seems to work well to make a placeholder component in order to get the compiling to work. 
However, I reached upon a new issue with the data being sent to the component.

Let's say I have the following 
```
const myData = { someText: 'Hello \n  My name is Johan' };
```
And send it to my component like
```
<MyComponent hydrate-client={{ data: myData }} />
```

With MyComponent.svelte containing the following:
```
<script>
  export let data;
  console.log('This is data', data);
</script>
```
This will log `{"someText":"Hello \  My name is Johan"}`, causing my newline character to be removed and only keeping the backslash. The use case for this is that we have markdown that will be converted to HTML in the final component.

Any ideas on how we can prevent these characters from getting escaped?

**Comment by myrsmedenstorytel** [comment]
I think I have found why our newline characters are disappearing, due to the following piece of code in `@elderjs/elderjs/build/utils/svelteComponent.js`
```
exports.replaceSpecialCharacters = (str) => str
    .replace(/&quot;/gim, '"')
    .replace(/&lt;/gim, '<')
    .replace(/&gt;/gim, '>')
    .replace(/&#39;/gim, "'")
    .replace(/\\\\n/gim, '')
    .replace(/\\"/gim, '"')
    .replace(/&amp;/gim, '&');
```

**Comment by nickreese** [comment]
@myrsmedenstorytel Thanks for the bug report. Will work on a fix.
