### ISSUE TITLE
Why is the documentation so broken?

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/elderjs#56]
Extra pages seems to be from another website, why is it like that?

There are lots of typos and grammatical errors on documentation pages as well.

Additionally the base template doesn't work with `npm run dev:server`, failing with the following error:

```
const haveDates = plugin.markdown[route].reduce((out, cv) => cv.frontmatter && cv.frontmatter.date && out);
                                                 ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.init (/elderjs-app/node_modules/@elderjs/plugin-markdown/index.js:79:50)
    at new Elder (/elderjs-app/node_modules/@elderjs/elderjs/build/Elder.js:77:24)
    at Object.<anonymous> (/elderjs-app/src/server.js:10:15)
```

**Comment by talha-asad** [comment]
I can help, but wanted to know if this is not intended

**Comment by nickreese** [comment]
@talha-asad the reduce issue is an oversight  but we havent seen that bug on 3 production sites that use it. Will push a fix today. 

Regarding typos I’m 100% open to specifics so we can improve. 

As to why the docs are hosted on ElderGuide.com that is the company who open sourced the software. 

I welcome constructive feedback. 👍
