### ISSUE TITLE
on:load from inside <svelte:head> of hydrated component not working

### ISSUE THREAD

**Issue by andrew-j-roberts** [Elderjs/elderjs#58]
<img width="780" alt="2020-10-18_21-07-05" src="https://user-images.githubusercontent.com/46111212/96391183-e7127080-1185-11eb-9829-a4cb281accf2.png">

Hi all,

I've been troubleshooting this issue since the summit and think I've boxed it into this issue. The on:load function that this script tag is supposed to trigger is not being run inside a client hydrated component, but I can verify that onMount is running and on the network tab I can see that the script source is being downloaded -- so before I investigate further I'd like to log this issue and see if there's an obvious bug it relates to.

I'm going to try bundling GSAP and see if that fixes things, but I want that sweet sweet 0 load time CDN cache hit if possible!

**Comment by nickreese** [comment]
@andrew-j-roberts the script should be showing up in your head but it may not be respecting the svelte directive and the function may be out of lexical scope (I think that is the name). Try using a standard onload and define/call the function there. 

No idea what the Svelte compiler emits in this case. Elder.js just SSRs what it gets.

**Comment by andrew-j-roberts** [comment]
Hey Nick, 

Thanks for the quick response. Makes sense. I tried using a standard onload but then ran into the problem where I couldn't tie the function to any reactive variable, essentially a variation of the same lexical scope problem that prevented the Svelte directive from calling the function. 

For me I'm just going to bundle GSAP, it's not a big issue especially with partial hydration. Feel free to close!
