### ISSUE TITLE
How to edit base template that elderjs uses

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/elderjs#59]
How can we update / edit the base template that elderjs uses for page rendering? Say if we wanted to change this `<meta charset="UTF-8" />` in the head section to something else? Also the base template seems to be bad, since it's following xhtml style meta tags.

**Comment by nickreese** [comment]
@talha-asad are xhtml tags not valid? 

As far as editing, depends on what exactly you want to edit. For the meta you’d need to disable the relevant hook `elderAddMetaCharsetToHead` by adding it to the `hooks.disable` array in your `elder.config.js` and then registering a new hook in it’s place. 

All of the core hooks can be found here: https://github.com/Elderjs/elderjs/blob/master/src/hooks.ts

Also look at the default function on `compileHtml`.

**Comment by talha-asad** [comment]
Thanks for the explanation, It just seems odd having xhtml style meta tags in a document that otherwise advertises itself as HTML 5. I would remove the trailing `/` on the meta tag in the default viewport hook, since it's unnecessary and basically not required in HTML 5.

Can you explain what IntersectionObserver and SystemJS is used for, and maybe we could add some information on them to the docs because right now, the template doesn't even have the s.min.js file that is being added into the default hook and it has to be fetched separately from the web and placed into the assets/static folder.

I can somewhat see that IntersectionObserver is being used for partial hydration. If you could explain a little bit more with hydration is, I can add it as a pull request with other improvements to the documentation and with some of these improvements if you approve of it.

**Comment by nickreese** [comment]
@talha-asad I was under the impression the closing slash is optional. 

They are both used during hydration. Intersection observer waits to mount until the component is within the viewport. 

SystemJs is how the components are bundled. There is a pr for module/nomodule support.
