### ISSUE TITLE
Running npm run dev:server works after a build

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/elderjs#61]
This might be an issue that is only relevant to me as I am getting more familiar with the inner workings of this well made framework, but just wanted to confirm if it is infact something that I have either misconfigured or misunderstood. 

Whenever I add files to the asset directory, the files are not copied over to the public folder automatically unless I manually do a `npm run build` before rerunning `npm run dev:server`. It seems nodemon, does pick that something has changed, but the files aren't copied over, I also found that that the default hook for copying files over to the public folder based on `copyAssetsToPublic` hook that comes along with your template doesn't exactly see if the file is actually a file or not a folder, and so if you have a folder named `type.js` it gets recognized as a file and produces an error, which is what it should do based on the default hook code.

I changed it so it looks like this now and it seems to be handling that edge case fine now, notice `fs.lstatSync` part in the if condition:

```js
{
    hook: 'bootstrap',
    name: 'copyAssetsToPublic',
    description: 'Copies ./assets/ to the "distDir" defined in the elder.config.js. This function helps support the live reload process.',
    run: ({settings}) => {
      // note that this function doesn't manipulate any props or return anything.
      // It is just executed on the 'bootstrap' hook which runs once when Elder.js is starting.

      // copy assets folder to public destination
      glob.sync(path.resolve(settings.rootDir, './assets/**/*')).forEach((file) => {
        const parsed = path.parse(file);
        // Only write the file/folder structure if it has an extension
        if (parsed.ext && parsed.ext.length > 0 && fs.lstatSync(file).isFile()) {
          const relativeToAssetsArray = parsed.dir.split('assets');
          relativeToAssetsArray.shift();

          const relativeToAssetsFolder = `.${relativeToAssetsArray.join()}/`;
          const p = path.parse(path.resolve(settings.distDir, relativeToAssetsFolder));
          fs.ensureDirSync(p.dir);
          try {
            fs.outputFileSync(
              path.resolve(settings.distDir, `${relativeToAssetsFolder}${parsed.base}`),
              fs.readFileSync(file),
            );
          } catch (e) {
            console.log('Error processing: ', file, e);
          }
        }
      });
    }
  }`

**Comment by nickreese** [comment]
@talha-asad files are only added on elder.js bootstrap. I’m open to suggestions if you think there is a better solution. 


That said, there was a pretty recent PR to the template’s hook that was merged in. Can you look at that and see if has the same issue?

**Comment by nickreese** [comment]
@talha-asad just thinking about this. You have two terminals open like explained in the docs right? One for rollup and one for the dev server. If not your svelte files may not be getting rebundled.
