### ISSUE TITLE
Documentation on using svelte plugins

### ISSUE THREAD

**Issue by The-BigDaddy** [Elderjs/elderjs#67]
Hello,

So while I'm enjoying working with Elder so far, one thing that I'm finding I need clarification on is using Svelte plugins.

In my case, it's [Svelma](https://c0bra.github.io/svelma) and (svelte-preprocess)[https://github.com/sveltejs/svelte-preprocess].

With Svelma, I'd like to customize colors and such, but then also let it be processed by PostCSS later.
So do I have something in `src/assets/styles.s[a|c]ss` where I import the Bulma stylesheet? The Svelma docs say to
put 

```
<script>
  import 'bulma/css/bulma.css'
</script>
```
 in `App.svelte` except Elder doesn't have that. So I imagine the `src/assets/styles.s[a|c]ss` route is the better option, maybe?

With svelte-preprocess, I'm a little confused as to how I'm to customize it. The documentation for it and what's in Elder's out of the box config is different, because there's honestly too many ways you can customize it. All I would like to have is to import `sass` and `postcss`, and then list out the PostCSS plugins I want to use. So something like:

```
import { sass, postcss } from 'svelte-preprocess';

module.exports = {
    preprocess: [
        sass({ implementation: 'node-sass' }),
        postcss({
            // plugins in here
        }),
    ],
}
```

Though I'm unsure if that would be correct.

Thank you for any help you give, and releasing Elder.js!

**EDIT:** Oh! Also with remark plugins, how are the module names determined? Because there's `frontmatter` and `extractFrontmatter` for `remark-frontmatter` and `remark-extract-frontmatter` respectively in `elder.config.js`, but them there's `remarkHtml` for `remark-html`. So what if I want to add more plugins?

**Comment by nickreese** [comment]
@The-BigDaddy use Layout.svelte as your “app” and use the recommended Svelte config and see if that works. I’ve never used either but will try and troubleshoot best I can.

**Comment by nickreese** [comment]
Closing this as there hasn’t been an update.
