### ISSUE TITLE
Unclear validation declaration

### ISSUE THREAD

**Issue by thisislawatts** [Elderjs/elderjs#68]
https://github.com/Elderjs/elderjs/blob/9793cab5a51cd2a6983b0c824fafaf16b62caf91/src/utils/validations.ts#L95

What is the desired behaviour here, this is currently marked as required but the message indicates there is default behaviour in place here.

**Comment by nickreese** [comment]
@thisislawatts This come down to how we're using the validations to build the output in the docs using the `yup.label()`. 

In `routes.ts` you'll see where we add the default.
