### ISSUE TITLE
Curious case : Updating list, dont work on elder js but work on svelte 

### ISSUE THREAD

**Issue by x4080** [Elderjs/elderjs#71]
I found strange issue, and then I created simple example to simulate it :

It just click to change content in list using #each
[REPL example](https://svelte.dev/repl/c49d7b60a70f4f0b8d5d191abf6090be?version=3.29.4)

And using elderjs :
```
npx degit Elderjs/template testlist
cd testlist
npm i
```
And edit src/components/Clock.svelte to

```
<script>
  let list = ['data1','data2'];

  function testclick() {
    list[1] = 'change';
    console.log(list);
  }
</script>

<br />

<main>
  {#each list as row, i (row)}
    <div on:click={testclick}>{row}</div>
  {/each}
</main>

```

In elderjs, when I click the list, console log show that it changed but the display is not changed

Thanks

**Comment by nickreese** [comment]
@x4080 this is due to how svelte handles reactivity. You need to actually assign it a new value to the array instead of
mutating the array.

**Comment by x4080** [comment]
Hi @nickreese love your talk on svelte summit, and thanks for quick reply

And yes I did try using assignment. And still not work, could you please visit the repl to show that it actually works in repl without assignment. Surprised me also

**Comment by sw-yx** [comment]
interesting. because you use = there is an $$invalidate call in the compiled output. and because you use an each block, the each is rerun on the array!

**Comment by nickreese** [comment]
@x4080 I think this is a Svelte issue and you're probably seeing differences due to how bundling is done. Here is a working REPL that should work in Elder.js: https://svelte.dev/repl/c97ab1b81e4644359da3e8d88f88b440?version=3.29.4

**Comment by x4080** [comment]
@nickreese Yes that works, maybe the key is using new const variable ?

Thanks anywat
