### ISSUE TITLE
Hydration not working in Layout.svelte

### ISSUE THREAD

**Issue by flauc** [Elderjs/elderjs#75]
I have this setup in my Layout.svelte file

```
<script>
  import Notification from '../components/shared/Notification.svelte';

  export let templateHtml, data;
</script>

<main>
  {@html templateHtml}
</main>

<Notification hydrate-client={{}} />
```
And in the notification I just have

```
<p>Test</p>
```

However, the test paragraph doesn't show up. If I use the component in the same way in Home.svelte or any other route it works properly.

**Comment by flauc** [comment]
I figured out that doing this works.

```
<Wrapper hydrate-client={{}} >
  <Notification />
</Wrapper>
```

With the wrapper just being a slot. However the Notification isn't hydrated that way and what I'm actually trying to achieve is to have a store define where the notification would open from any other component in the app. Is this possible with elder.js?

**Comment by nickreese** [comment]
@flauc You can't use slots `with hydrate-client={{}}` because the native Svelte mount code doesn't support it. But, you can just use notification inside the `Wrapper`. 

Just remember that under the hood `hydrate-client` is mounting a new component and is literally just a helper  around this:

```
import App from './App.svelte';

const app = new App({
	target: document.body,
	props: {
		// assuming App.svelte contains something like
		// `export let answer`:
		answer: 42
	}
});
```

**Comment by nickreese** [comment]
@flauc The reality is that you can do everything you can do in a normal svelte app. You're just pushing it 1 layer of components deeper.

**Comment by flauc** [comment]
Thank you for the quick response. I see what you're saying. However if I just do this in my Layout

```
<DynamicWrapper hydrate-client={{}} />
```

The DynanmicWrapper just being 

```
<script>
  import Notification from './Notification.svelte';
</script>

<Notification />
```

And the Notification:

```
<p>test</p>
```

I still don't see the paragraph. 
I think there is a problem with hydration in the Layout.svelte file because if I do the same thing anywhere else it seems to work nicelly.

**Comment by flauc** [comment]
Unfortunently even though it does render the paragraph when used in route rather then the layout the stores still don't work. For instance I have a `stores.js` from which I export a writable store and it seems like two different components both get their own store rendering them unable to communicate.

**Comment by nickreese** [comment]
@flauc stores can be broken on dev as the current version of Elder.js bundles components as separate stand alone files instead of multipart. This causes the stores to break in exchange for faster reload #44 Improvement coming on #42 which just is waiting on code review... this makes the split rollup opt-in among other things.

**Comment by nickreese** [comment]
@flauc Tried to recreate this today and can't if you can push a demo repo I'll investigate.

**Comment by flauc** [comment]
@nickreese Thank you for your continuing effort. I was on version `1.0.4` and there it doesn't work. However now that I've updated to `1.1.1` it works perfectly. 

I feel very optimistic about migrating to elder.js!

**Comment by nickreese** [comment]
@flauc Woot! Awesome. Glad it is working for you. 👍
