### ISSUE TITLE
Different hydration options for different components

### ISSUE THREAD

**Issue by myrsmedenstorytel** [Elderjs/elderjs#77]
Hello! I experience an issue with the hydration options.
Let's say I have multiple components on my page that are client-side hydrated. 
Then it seems like the settings for the first component is what affects the loading. 

## How to reproduce:
Clone the template and copy the `Clock` component twice, with identical copies called something like `Alock` and `Block`. 
Import them at the top
```
import Clock from '../../components/Clock.svelte';
import Block from '../../components/Block.svelte';
import Alock from '../../components/Alock.svelte';
```

and use all three in the place where the one currently is used in `Home.svelte`
```
<Clock hydrate-client={{}} hydrate-options={{ loading: 'eager', preload: true }} />
<Block hydrate-client={{}} hydrate-options={{ loading: 'lazy' }} />
<Alock hydrate-client={{}} hydrate-options={{ loading: 'lazy' }} />
```

With this setting, all three components will be eagerly loaded and preloaded in the top of the HTML file. 
I would expect only the first component to have this behaviour and the rest of them to be lazy-loaded.

**Comment by nickreese** [comment]
@myrsmedenstorytel Thanks for the bug report. Did a major refactor of how we mount Svelte components to make it all much more test able. Ironically it was the absolutely last file that I did that had the bug. Push a fix shortly #81
