### ISSUE TITLE
Creating an index page for all posts

### ISSUE THREAD

**Issue by The-BigDaddy** [Elderjs/elderjs#82]
I'd like to have the `blog/` page broken up to where I have

- `https://my-site.com/blog/` is containing all of the created posts

- `https://my-site.com/blog/this-is-a-post` is a specific post.

I know I can pass a different template to `blog/route.js`...

```javascript
module.exports = {
  template: 'BlogPost.svelte',
  permalink: ({ request }) => `blog/${request.slug}/`,
  all: () => [],
  data: {},
};
```

...but how do I create a singular index page? Simply have a `Blog.svelte` file for the default route?

**Comment by nickreese** [comment]
Look at the Home of the template to see how to get access to all posts.

**Comment by The-BigDaddy** [comment]
So it's hook related?

I have to have 

```javascript
data: ({ data }) => {
    // The data function populates what data should be in available in our Svelte template.
    // Since we will be listing out Elder.js's hooks, we make sure to populate that on the data object so it can be looped through
    // in our Svelte template.
    data.hookInterface = hookInterface;
    return data;
 }
```

In `routes/blog/route.js` order to then use
 
```javascript
export let data, helpers;
const hooks = data.hookInterface.map((hook) => ({ ...hook, link: helpers.permalinks.hooks({ slug: hook.hook }) }));
```

In `Blog.svelte`?

Am I understanding this correctly?

**Comment by nickreese** [comment]
@The-BigDaddy the plugin adds it to the data object via hooks: 

```
<div class="blog">
  <div class="entries">
    {#each data.markdown.blog as blog}
      <BlogTeaser {blog} {helpers} />
    {/each}
  </div>
</div>
```

Exactly the same.

**Comment by The-BigDaddy** [comment]
@nickreese 

This doesn't exactly answer my question: 

What I'm wanting to do is have the link `https://my-site.com/blog/` be a list of all the posts I have, with `Blog.svelte` being the index page, so to speak:

```
<script>
  import BlogTeaser from '../../components/BlogTeaser.svelte';
  export let data, helpers; // data is mainly being populated from the /plugins/edlerjs-plugin-markdown/index.js
</script>

<svelte:head>
  <title>Blog Posts</title>
</svelte:head>

<section class="section">
  <div class="container is-fluid has-text-centered">
    <h2 class="title is-2">Posts</h2>
  </div>
</section>
<hr/>
<section class="section">
  <div class="container is-fluid has-text-left">
    {#each data.markdown.blog as blog}
      <BlogTeaser {blog} {helpers} />
    {/each}
  </div>
</section>
```

And then `BlogPost.svelte` to be the template for any `https://my-site.com/blog/:slug`

```
<script>
  export let data;
  const { html, frontmatter } = data;
</script>

<svelte:head>
  <title>{frontmatter.title}</title>
  <meta name="description" content={frontmatter.description} />
  <meta name="keywords" content={frontmatter.keywords} />
</svelte:head>

<article>
  <section class="hero">
    <div class="hero-body">
      <div class="container is-fluid has-text-centered">
        <h3 class="title is-4">{frontmatter.title}</h4>
        <h4 class="subtitle is-5">{frontmatter.description}</h5>
      </div>
    </div>
  </section>
  <hr />
  <section class="section">
    <div class="container is-fluid has-text-centered">
      {#if html}
        {@html html}
      {:else}
        <h5 class="title is-5">Oops! There's nothing here!</h5>
      {/if}
    </div>
  </section>
</article>
```

While what you mentioned was helpful, it doesn't exactly answer this part of my question.

To maybe explain better, in [Nuxt]() you can have `pages/blog/_slug.vue` for each post (`https://my-site.com/blog/:slug`), and `pages/blog/index.vue` to be the index page with all of the posts you've made (`https://my-site.com/blog/`).

How this would work with Elder's routing is not explained. I know you can have a permalink like so,

```
// just the contact page as an example
all: () => [{ slug: 'contact' }],
permalink: ({ request }) => request.slug
```

But how would you do this for `page/` and then more specifically `page/:slug`?

**Comment by nickreese** [comment]
@The-BigDaddy ah now it is clearer. You can set it in your frontmatter of each post. Also this PR would give you a function to control it: https://github.com/Elderjs/plugins/pull/48

**Comment by nickreese** [comment]
In more detail: basically under the hood the markdown plugin is setting all of the `request` object slugs which then get run through the `permalink` function of the route. https://github.com/Elderjs/template/blob/f194acdadeda70a68f1de558c33d9190d85f5065/src/routes/blog/route.js#L16

If you wanted to adjust the slug for each markdown file you can add it in the frontmatter. 

To add an index of the blog you’ll probably want a new route. Just hardcode the permalink function to return “/blog/”. 

This should get you what you needed.

**Comment by nickreese** [comment]
Explicit routing is different than other frameworks. If you can help improve the docs where it is lacking that would be great.

**Comment by The-BigDaddy** [comment]
Interesting, but how do I have each post use a separate template than the one for `/blog/`?

Can I tell the markdown plugin a template it should use? Or can I set in the frontmatter as well?

I'd also think having distinct `/page/` and `/page/:slug` routes would be useful in other means besides blogging. Say like an online store: you have `/shop/` that's the main store page, and `/shop/:slug` for each product. Potentially. There could be better ways to manage an online store than that.

**Comment by nickreese** [comment]
@The-BigDaddy please read the docs on routes. All of this is covered. You have two separate routes. One for the blog index page and one for each blogpost. https://elderguide.com/tech/elderjs/

All of this is covered in detail. The plugin is just populating the all array for the route specified.

**Comment by The-BigDaddy** [comment]
I can understand the routes. That's not my issue at the moment.

From what I understand, to get the desired outcome I'd have to have this in `routes/blog/route.js`:

```javascript
module.exports = {
  template: 'Blog.svelte',
  permalink: ({ request, settings }) => `/${request.blog.slug}/${request.slug}/`,
  all: async () => {
    return [{ blog: { slug: 'blog' } }];
  },

  data: ({ data }) => {
    return data;
  },
};

```

And this will allow for distinct pages: one being `/blog/` where I can list all of my posts and potentially have pagination, and `/blog/some-post-title/` this is a single post itself; correct? It's janky, but it will do what I want if I'm understand correctly, yes? If not, then I'm going to need clarification.

Either yes or not, what I also really need answered is 

> ...how do I have each post use a separate template than the one for /blog/?

> Can I tell the markdown plugin a template it should use? Or can I set in the frontmatter as well?

So in the above you see I specified `template: Blog.svelte`. That's specifically for `/blog/`. But I want `/blog/some-post-title` to use `BlogPost.svelte` that's found in the same directory, `/routes/blog/`, for individual posts. In the basic Elderjs template, [`Blog.svelte` is for singular posts](https://github.com/Elderjs/template/blob/master/src/routes/blog/Blog.svelte), as indicated by

```html
<div class="title">
  <h1>{frontmatter.title}</h1>
  {#if frontmatter.author}<small>By {frontmatter.author}</small>{/if}
</div>
```

being that `frontmatter` will only grab data from a singular post.

 I want `BlogPost.svelte` to be for singular posts, _not_ `Blog.svelte`. It is not directly specified in the docs how to do this, nor in the Elderjs markdown plugin itself. Do I need to have something like [how Sapper has `[slug].svelte`](https://sapper.svelte.dev/docs#Pages) (shown in the 4th paragraph, 3rd code block)?

**Comment by nickreese** [comment]
I think I follow the issue. Here is how you would specify different templates in the `route.js` and you can do something similar based on some field in frontmatter of the individual post from within `BlogPost.svelte`. 

`Route.js`: 

```javascript
module.exports = {
  template: 'Blog.svelte',
  permalink: ({ request, settings }) => `/${request.blog.slug}/${request.slug}/`,
  all: async () => {
    return [{ blog: { slug: 'blog' }, template: 'BlogIndex' }];
  },

  data: ({ data }) => {
    return data;
  },
};
```

`Blog.svelte`
```svelte
<script>
  import BlogIndex from './BlogIndex.svelte';
  import BlogPost from './BlogPost.svelte';

  export let settings, data, helpers, request;

  let component = BlogPost;

  if (request.template === 'BlogIndex') {
    component = BlogIndex;
  } 
</script>

<svelte:component this={component} {settings} {data} {helpers} {request} />
```

**Comment by The-BigDaddy** [comment]
Ok so I didn't know that the object returned by `all` could have a `template` property.

Thank you.

**Comment by nickreese** [comment]
@The-BigDaddy it can have any property you want. Some might get shadowed by the system such as “route”, “permalink”, and “type” but it is anything you need it to be.

**Comment by michael0liver** [comment]
> I think I follow the issue. Here is how you would specify different templates in the `route.js` and you can do something similar based on some field in frontmatter of the individual post from within `BlogPost.svelte`.
> 
> `Route.js`:
> 
> ```js
> module.exports = {
>   template: 'Blog.svelte',
>   permalink: ({ request, settings }) => `/${request.blog.slug}/${request.slug}/`,
>   all: async () => {
>     return [{ blog: { slug: 'blog' }, template: 'BlogIndex' }];
>   },
> 
>   data: ({ data }) => {
>     return data;
>   },
> };
> ```
> 
> `Blog.svelte`
> 
> ```svelte
> <script>
>   import BlogIndex from './BlogIndex.svelte';
>   import BlogPost from './BlogPost.svelte';
> 
>   export let settings, data, helpers, request;
> 
>   let component = BlogPost;
> 
>   if (request.template === 'BlogIndex') {
>     component = BlogIndex;
>   } 
> </script>
> 
> <svelte:component this={component} {settings} {data} {helpers} {request} />
> ```

Hi, first off thanks for Elderjs its really amazing!

I am trying to get the example code you gave working and I keep getting an error:
```
/Users/michaeloliver/Development/Personal/elderjs-app/node_modules/@elderjs/elderjs/build/Elder.js:199
                            throw new Error(`Request for ${routeName} is missing a slug property.`);
                                  ^

Error: Request for blog is missing a slug property.
```

**Comment by ViorelMocanu** [comment]
I have the exact same issue and I've tried the latter method to no avail. The blog posts load correctly after having been passed through the `Blog.svelte` equivalent, but the index just throws a `Not Found` on me incessantly.

My blog folder is `informatii-utile` (which has all the `.md` files inside), my routing proxy is `InformatiiUtile.svelte` and the two templates are `BlogIndex.svelte` and `BlogPosts.svelte`.

I will be reproducing the relevant files here in hopes that someone might help:

### route.js
`module.exports = {
  template: 'InformatiiUtile.svelte',
  data: ({ data }) => {
    return data;
  },
  all: async () => {
    return [
      {
        'informatii-utile': { slug: 'informatii-utile', template: 'BlogIndex' },
        template: 'BlogIndex',
      },
    ];
  },
  permalink: '/informatii-utile/:slug/',
};
`

### InformatiiUtile.svelte
`<script>
  import BlogIndex from './BlogIndex.svelte';
  import BlogPost from './BlogPost.svelte';
  export let data, helpers, request, settings;
  const { html, frontmatter } = data;

  let component = BlogPost;
  if (request.template === 'BlogIndex') {
    component = BlogIndex;
  }
</script>

<svelte:component this={component} {settings} {data} {helpers} {request} />
`

Thank you in advance!
