### ISSUE TITLE
Component not updated using latest version

### ISSUE THREAD

**Issue by x4080** [Elderjs/elderjs#83]
Hi, changes in component is not updated (seems like there's 2 version, server rendered is correct but hydrated not changed)

Steps :
- npx degit Elderjs/template projecta
- cd projecta
- npm i

- npm run dev:rollup 
- npm run dev:server

- open localhost:3000

- Edit routes/home/Home.svelte to
```
<script>
  import Clock from "../../components/Clock.svelte";
  
  </script>
  <Clock hydrate-client={{ }}/>
```
--> It will display clock only

Open src/components/Clock.svelte, change it to :
```
Clock is here
```

And SVG clock is still running ('Clock is here' text appears and back to SVG clock)

**Comment by nickreese** [comment]
@x4080 that is strange. Make sure rollup has run for both and the server has restarted.

**Comment by x4080** [comment]
@nickreese Yes I found it strange also, and yes rollup is running and even if I restarted the rollup and server still not updating

**Comment by x4080** [comment]
@nickreese I retry again to make sure and it still stands. I stop the rollup and server, and re run rollup and server again
and the result is still clock (but now the svg is gone, so black circle)

Very strange indeed

**Comment by nickreese** [comment]
@x4080 the ssr version is updated but the client version is not. That is the only way it happens.

**Comment by x4080** [comment]
Ok, hope you can replicate this on your machine

**Comment by nickreese** [comment]
Can you verify between rollups both your `/public/svelte` and `/___ELDER___/compiled` Folders are getting deleted? This could be a hashing issue.

**Comment by x4080** [comment]
I'm on mobile now, will check it later

**Comment by x4080** [comment]
Hi, @nickreese 

Sorry for late reply, content of /public/svelte  and /___ELDER___/compile is very different, how can I find the difference ?
