### ISSUE TITLE
Route organization question

### ISSUE THREAD

**Issue by justinmoon** [Elderjs/elderjs#85]
I'm making an educational site. It will look similar to [this](https://fireship.io/courses/): a list of courses, each of which contains a list of lessons (markdown with a video link in front matter).

What would be the best way to organize this?

In particular, each "lesson page" will need to display a list of the other lessons in that same course. This would be like `Blog.svelte` in the template showing a list of the other blog posts.

Thanks!

**Comment by nickreese** [comment]
@justinmoon Routing is wide open and left up to the user. I'm assuming you're using the `markdown` plugin.

At a high level, I'd implement it similar to this comment: https://github.com/Elderjs/elderjs/issues/82#issuecomment-720109364

1. Each course would be its own route. 
1. Then within the `Blog.svelte` (or whatever your template is) you have access to all of the parsed markdown on the `data.markdown` object.
