### ISSUE TITLE
Configure html language code

### ISSUE THREAD

**Issue by meigo** [Elderjs/elderjs#87]
Currently it seems to be hardcoded to english

```html
<html lang="en">
```

Could overwrite it in hooks.js but would be nicer to have it as an elder config option.

**Comment by nickreese** [comment]
Hey @meigo, thought about this a lot.

You'll need to add the relevant hook to the `hooks.disable` array in your `elder.config.js`.

And overwrite this hook:

```javascript
  {
    hook: 'compileHtml',
    name: 'elderCompileHtml',
    description: 'Creates an HTML string out of the Svelte layout and stacks.',
    priority: 50,
    run: async ({ request, headString, footerString, layoutHtml }) => {
      return {
        htmlString: `<!DOCTYPE html><html lang="en"><head>${headString}</head><body class="${request.route}">${layoutHtml}${footerString}</body></html>`,
      };
    },
  },
```

There are lots of cases where the lang tag is dynamic so hooks are the right place to do this.

**Comment by meigo** [comment]
Handy, thanks Nick!
