### ISSUE TITLE
Wrong data attribute value

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/elderjs#89]
In a svelte component

```<div data-parallaxanimation={`[{property: "transform", value:" translate3d(0,{{val}}rem,0)", initial:"4", mid:"0", final:"-4"}]`}>```

is being rendered as:

```<div data-parallaxanimation="[{property: &quot;transform&quot;, value:&quot; translate3d(0,{{!val!}}}rem,0)&quot;, initial:&quot;4&quot;, mid:&quot;0&quot;, final:&quot;-4&quot;}]">```

Notice the `{{!val!}}` part, this is something that is happening since we upgraded to the latest version.

**Comment by nickreese** [comment]
In the last release we changed when shortcodes are processed. 

What you are seeing is an error when the shortcode is detected. 

The quickest fix is to change your shortcode open and closing brackets to be non-default. 

This code appears to be very non-standard. There may be a better way to do what you’re looking to do.

**Comment by talha-asad** [comment]
Hmm, what way would you propose, it seems like a bug to me, as I was under the impression anything started with `{`` and ``}` is supposed to be outputted as is.
