### ISSUE TITLE
route.js: access helper in permalink

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#90]
**Is your feature request related to a problem? Please describe.**
I start working on a i18n plugin which , among other things, generate requests and permalink and save it to a dictionnary in `plugin` for later use (e.g: `/pikachu` become `/fr/pikachu` and `/en/pikachu`). 

Since `permalink` doesn't have access to helper, it make it more difficult to add permalink to a dictionnary and to implement some features, for examples:
- "prefix_except_default" (add i18n.code except for the default locale)
- "permalink replacement" if we want to change the permalink for different locales, (e.g: `/en/bulbasaur` and `/fr/bulbizarre`)
- and probably others..

**Describe the solution you'd like**
 I can add an helper to generate i18n requests in `all` as the following:
```
  all: async ({ helpers }) => helpers.i18n.requests([{ slug: 'pikachu' }])
```
So it can be great to be able to do the same for `permalink` like this:

```
  permalink: ({ request, helpers }) => helpers.i18n.permalink(request, `pokemon/${request.slug}/`),
```

**Describe alternatives you've considered**
- I consider rewriting the `slug` params in `allRequests` hook but it doesn't feel right at all and will add others issues for hreflang and probably other things.
- we can also add `all`, `permalink` and `data` hooks but it can probably add complexity by hiding some functions, so we should avoid it I guess.

**Comment by nickreese** [comment]
@kiuKisas 

Interesting. Your way will work and I think the permalink function likely should have access to the helpers. (see below)

That said, you could also change the array returned by `helpers.i18n.requests` to include an `i18nPermalink` and use that in your `permalink` function `permalink: ({request}) => request.i18nPermalink,` instead of calling the helpers. 

(NOTE: Elder.js does enforce a `slug` to be on each request to keep people from shooting themselves in the foot, the `slug` doesn't have to be used in generating the `permalink`.)



## Helpers to Permalink 

If you still want to explore adding the helpers to the permalink here is how:

You'll need to add the `i18n` helper to the `helpers` object on `bootstrap`.

Before we implement this in the core, can you test it locally and make sure it works well for you?

Look for this line in your local copy of Elder.js: `node_modules/@elderjs/elderjs/build/Elder.js`

```
                    request.permalink = await this.routes[request.route].permalink({
                        request,
                        settings: { ...this.settings },
                    });
```

and change it to:
```
                    request.permalink = await this.routes[request.route].permalink({
                        request,
                        settings: { ...this.settings }, // this should be a readonly proxy... will fix this next release. 
                        helpers: createReadOnlyProxy_1.default(this.helpers, 'helpers', `${routeName} all function`),
                    });
```

## Other
Have you given thought to how users would use the `helpers.permalinks.pokemon({request})` helper to build links? It seems that the signature of the `helpers.i18n.permalink` may be a bit limiting.

**Comment by kiuKisas** [comment]
I have to admit, I stuck with the idea of having a `request` as light as possible that I didn't even think of including an `i18nPermalink` as you mention. 

That said, I made the change into my local copy and it works as expected, I'll make a PR asap if you want to.

##  Other
Currently in my early version, the `helpers.i18n.permalink` signature is `(basePermalink:string, request:request) : string`, this way the user still can define a permalink, then it will be "converted" according to `request.i18n`and save into a dictionnary living in the plugin scope (and will be accessible in data), `request.slug` is used as an id between locales . 
So, for an early example:
- config
```
// set in elder.config.js
plugin.config.locales =   [
        { code: 'fr', iso: 'fr-FR' },
        { code: 'en', iso: 'en-US' },
      ],
```
- helpers
```
  all: async ({ helpers }) => helpers.i18n.requests([{ slug: 'pikachu' }]),

// all: [ 
//     { slug: 'pikachu', i18n: { code: 'fr'} },
//     { slug: 'pikachu', i18n: { code: 'en'} }, 
// ]

  permalink: ({ request, helpers }) => helpers.i18n.permalink(`/pokemon/${request.slug}/`, request),

// permalink: /en/pokemon/pikachu
// permalink: /fr/pokemon/pikachu
```
And it's saved in a dictionnary through the permalink helper, it currently look like that:
```
[
  {
    "slug": "pikachu",
    "locales": [
      {
        "locale": "fr",
        "permalink": "/fr/pokemon/pikachu/"
      },
      {
        "locale": "en",
        "permalink": "/en/pokemon/pikachu/"
      }
    ]
  }
]
```

**Comment by nickreese** [comment]
@kiuKisas I like it. Question before the PR.

If all returns: 
```javascript
 [ 
   { slug: 'pikachu', i18n: { code: 'fr'} },
   { slug: 'pikachu', i18n: { code: 'en'} }, 
]
```

By the time it gets to `permalink()` it actually looks like so: 

```javascript
 [ 
   { slug: 'pikachu', i18n: { code: 'fr'} , route: 'pokemon' },
   { slug: 'pikachu', i18n: { code: 'en'} , route: 'pokemon' }, 
]
```

While I'm not sure this is a pattern we want to encourage outside of `i18n` there seems to be an opportunity to centralize your routing. 

`permalink: ({request, helpers}) => helpers.i18n.permalink(request)`

Then you could actually define the routing in one central place. 

This makes things more usable with `<a href="{helpers.permalinks.pokemon({request})}>` in your Svelte templates. 

I'd encourage you to explore that idea. Happy to support a PR for this. :)

**Comment by kiuKisas** [comment]
Ho ok, my bad, naming my function that generate the permalink`helpers.i18n.permalink`confuse me when you talk about the helper to get permalink in a svelte component. 

I tried and we don't have access to `helpers` when we call `helpers.permalink`, resulting in `undefined` when it try to call `helpers.i18n`. Say like that it make sense and that's probably why it was not implement.

I dig into the code and made a quick and dirty fix that doesn't feel right but I can continue for now; and we should avoid this kind of "circular dependencies" anyway.
## Quick fix in a nutshell
### utils/permalinks.js
```
12: out[cv] = (data, helpers = {}) => `${prefix}${routes[cv].permalink({ request: data, helpers, settings })}`;
```
### src/routes/pokemon/Pokemon.svelte
```
helpers.permalinks.pokemon({ slug: 'pikachu', lang: 'fr'}, helpers)
```
I also consider binding the `helpers` after the `middleware` hook (the last hook with mutable helpers) to avoid the helpers parameter, but I prefer to think about an other way to manage that. 

NB: I replace `i18n: { code: 'fr' }` by `lang: 'fr'`

## My proposal for that
This issue highlight the fact that `permalink` is called when we call `helpers.permalink`, so we definitely don't want to touch the dictionary there. You're idea to make it between `all` and `permalink` fit way better so I'll go for it.

To recap, I need to set some `helpers` in my plugin that:
- is outside the current `helpers` scope (to avoid a weird circular dependency)
- doesn't need `plugin` data (but should be able to if we want to support more use cases)
-  is accessible in at least `permalink` (but should be accessible in all, permalink and data)
--> For that, it's better to set it before all currents hooks as the permalink helper is define before hooks call. 

So I was thinking about adding a key in the plugin object, that can be name`helpers` or `externalFunctions` or even `methods` if we add an access to the `plugins` data (I'll go with the last one for the example).

In my head, it will look like this:
#### plugins/pluginName/index.js
```
const plugin = {
name: 'myAwesomePlugin'
...
methods: {
  base: () => console.log("I'm pure !"),
  simple: ({plugins}) => console.log('access to plugins'),
  other: ({plugins}, otherValues) => console.log('I have other parameters !')
}
...
}
```
Then we can set it in, let's says, `methodsPlugins` object, that look like:
```
{
  myAwesomePlugin: { base, simple, other},
  ...
}
```
We can add it to `utils/permalink.js` permalink call since it will be set before, and we will have a `route.js`as the following:
```
module.exports = {
  ...
  permalink : ({request, {myAwesomePlugin}}) => myAwesomePlugin.other('stuffs') 
  # all methods will be bind with plugins data if we go with that
  ...
}
```

My only concern is that is really similar to the actual `helpers` and can be confusing..

What are you though on that ?

**Comment by nickreese** [comment]
@kiuKisas Lots going on in this message but here is my thought.

The default `helpers.permalinks` is this: 

```
const permalinks = ({ routes, settings }) =>
  Object.keys(routes).reduce((out, cv) => {
    const prefix = settings.server && settings.server.prefix ? settings.server.prefix : '';
    out[cv] = (data) => `${prefix}${routes[cv].permalink({ request: data, settings })}`;
    return out;
  }, {});
```
I'd suggest the plugin adds its own modified version of this function on `i18n.permalinks` add that object to `helpers` object on the `bootstrap` hook. 

By doing this you aren't polluting the other helpers and you could make your functions available across the entire system. 

We'd still need the PR to add the `helpers` object to the `permalink()` function.

This results in the permalink function looking like so:
```
permalink: ({request, helpers}}) => helpers.i18n.permalinks[request.route]({request})
```

You could simplify things by modifying `helpers.i18n.permalinks()` to just take the `request`.

**Comment by kiuKisas** [comment]
Sure I can do that, seems good enough.
But isn't a bit weird to break the default`helpers.permalink` if an user use an`helper` in permalink function ? The use case is small I  guess but I think we should at least write it somewhere.

**Comment by nickreese** [comment]
@kiuKisas Ah, I'm not saying break the usage of the default helper, just add your own plugin specific helper that is accessible on `helpers.i18n.permalinks`. 

Basically you can namespace all of this in `i18n` and not worry about messing with the core.

**Comment by kiuKisas** [comment]
Sure, I understand, what I mean is, once we'll add `helpers` object to the `permalink()` function, if we use this feature, `helpers.permalink` will not work (and we have to add a new permalinks helper as you suggest) . 
It can be confusing for someone who is not award of that; so  I propose to write something about it in the documentation once the PR is merge.
