### ISSUE TITLE
How can I set 2 different svelte templates, through one route file

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/elderjs#91]
I have a `blog` folder in my routes directory with 2 templates, `Index.svelte` and `Post.svelte`,

I can add 2 slugs to my route.js file, but how can I specify to use a different templates in case of homepage or post?

Should I use a svelte if condition? I tried using a function in the route for template property, but it doesn't work.

**Comment by nickreese** [comment]
@talha-asad see this: https://github.com/Elderjs/elderjs/issues/82#issuecomment-720109364
