### ISSUE TITLE
Maybe Hydration Issue With Svelte Store

### ISSUE THREAD

**Issue by bgjehu** [Elderjs/elderjs#94]
I have a component using a Svelte store to hide and show a `<h1>`.
It behaviors differently from the Svelte Repl and within the Elderjs.
I couldn't figure out why, and hoping to get some help here. Thank you.

Svelte Repl
[https://svelte.dev/repl/55e3eb0a8eee408eade03f5fc378751d?version=3.29.7](https://svelte.dev/repl/55e3eb0a8eee408eade03f5fc378751d?version=3.29.7)

Repo of the component within Elderjs
[https://github.com/bgjehu/elderjs-hydration-issue](https://github.com/bgjehu/elderjs-hydration-issue)

**Comment by micha-lmxt** [comment]
Hi, how does it behave differently? I copied your component into my project and could not see a difference.

**Comment by bgjehu** [comment]
> Hi, how does it behave differently? I copied your component into my project and could not see a difference.

in this [repo](https://github.com/bgjehu/elderjs-hydration-issue), the `Toggle.svelte` component does not hide and show on the button clicked? And It does while copied into your project?

**Comment by nickreese** [comment]
Make sure you are on the latest version. I can't recreate this.
