### ISSUE TITLE
How do I render a route / svelte component through node?

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/elderjs#96]
I added a function for serving 404 route / template incase of a 404 to polka in `server.js` like the following:

```js
const server = polka({
  onNoMatch: (req, res, next) => {
    console.log('404 Error: ', req.url);
    
  }
});
```

How can I render a regular elderjs route here?

**Comment by nickreese** [comment]
For ssr look at the `middleware` hook id you want it through elder.js. It’ll be fiddly but it is totally doable. The docs could use an example... but it is a perfect use case for a plugin.
