### ISSUE TITLE
Permalink ending by a slash

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#98]
I notice that all permalinks ends with a slash.
I can delete them manually and can probably add a hook for that but does a better workaround exist to have permalinks without a slash at the end ?
Thank's :)

**Comment by nickreese** [comment]
@kiuKisas This is enforced by design because of the SSG nature of Elder.js. All paths are actually `foo/index.html` and by enforcing consistency it keeps people from shooting themselves in the foot SEO wise. 

I'm open to different opinions here. 

See `wrapPermalinkFn.ts`

**Comment by kiuKisas** [comment]
Seems fair, I'll stay with an helpers as I don't think editing the code for that worth it

**Comment by eight04** [comment]
It would be nice to document this behavior. I was expecting elderjs mapping `/foo` to `/foo.html` and `/foo/` to `/foo/index.html`.

It should also throw an error if `route.permalink` doesn't end with a slash.

**Comment by nickreese** [comment]
`wrapPermalinkFn.ts`:

```
      if (permalink.slice(-1) !== '/') {
        if (settings.debug.automagic) {
          console.warn(
            `The permalink function for route "${routeName}" does not return a string with a ending slash. One has been added. To disable this warning, fix the function's return value to include a ending slash.`,
          );
        }
        permalink = `${permalink}/`;
      }
```

@eight04 it is behind a flag. 

We could totally make it a warning.
